/** @internal Development-only demo finance dataset — never import directly in UI. */

import type {
  AccountingIntegration,
  FailedPayment,
  FinanceOverviewMetrics,
  FinancePayout,
  FinanceRefund,
  FinanceReport,
  FinanceTransaction,
  MonthlyInvoice,
  MonthlyRevenuePoint,
  PayoutSummary,
} from "./types";

export const ROLLING_TWELVE_MONTH_REVENUE = 87_250;

export const MONTHLY_REVENUE_HISTORY: MonthlyRevenuePoint[] = [
  { month: "Jul 2025", revenue: 6120 },
  { month: "Aug 2025", revenue: 7450 },
  { month: "Sep 2025", revenue: 6980 },
  { month: "Oct 2025", revenue: 7210 },
  { month: "Nov 2025", revenue: 6840 },
  { month: "Dec 2025", revenue: 8100 },
  { month: "Jan 2026", revenue: 7650 },
  { month: "Feb 2026", revenue: 7020 },
  { month: "Mar 2026", revenue: 7890 },
  { month: "Apr 2026", revenue: 8240 },
  { month: "May 2026", revenue: 8560 },
  { month: "Jun 2026", revenue: 4190 },
];

export const MONTHLY_INVOICES: MonthlyInvoice[] = [
  {
    id: "inv_2026_05",
    periodLabel: "May 2026",
    periodStart: "2026-05-01",
    periodEnd: "2026-05-31",
    totalSales: 8560,
    totalBookings: 198,
    grossRevenue: 8560,
    platformFees: 171.2,
    stripeFees: 145.8,
    refunds: 95,
    netPaidOut: 8148,
    payoutDestination: "Barclays business account ···4821",
    payoutDates: ["2026-06-03T09:00:00Z", "2026-06-17T09:00:00Z"],
    vatNet: 7133.33,
    vatAmount: 1426.67,
    lineItems: [
      {
        bookingReference: "BK-1038",
        activityName: "Junior Tennis Camp",
        venue: "Oakwood Tennis Club",
        grossAmount: 60,
        netAmount: 50,
        vatAmount: 10,
        platformFee: 1.2,
        stripeFee: 1.1,
        netPayout: 57.7,
        paymentDate: "2026-05-28T09:15:00Z",
        payoutDate: "2026-06-03T09:00:00Z",
      },
      {
        bookingReference: "BK-1035",
        activityName: "Creative Dance Workshop",
        venue: "Town Hall Studio",
        grossAmount: 35,
        netAmount: 29.17,
        vatAmount: 5.83,
        platformFee: 0.7,
        stripeFee: 0.73,
        netPayout: 33.57,
        paymentDate: "2026-05-22T18:40:00Z",
        payoutDate: "2026-06-03T09:00:00Z",
      },
      {
        bookingReference: "BK-1020",
        activityName: "Junior Tennis Camp",
        venue: "Oakwood Tennis Club",
        grossAmount: 60,
        netAmount: 50,
        vatAmount: 10,
        platformFee: 1.2,
        stripeFee: 1.1,
        netPayout: 57.7,
        paymentDate: "2026-05-15T13:12:00Z",
        payoutDate: "2026-06-03T09:00:00Z",
      },
    ],
  },
  {
    id: "inv_2026_04",
    periodLabel: "April 2026",
    periodStart: "2026-04-01",
    periodEnd: "2026-04-30",
    totalSales: 8240,
    totalBookings: 186,
    grossRevenue: 8240,
    platformFees: 164.8,
    stripeFees: 140.2,
    refunds: 35,
    netPaidOut: 7900,
    payoutDestination: "Barclays business account ···4821",
    payoutDates: ["2026-05-06T09:00:00Z", "2026-05-20T09:00:00Z"],
    vatNet: 6866.67,
    vatAmount: 1373.33,
    lineItems: [
      {
        bookingReference: "BK-1016",
        activityName: "Creative Dance Workshop",
        venue: "Town Hall Studio",
        grossAmount: 35,
        netAmount: 29.17,
        vatAmount: 5.83,
        platformFee: 0.7,
        stripeFee: 0.73,
        netPayout: 33.57,
        paymentDate: "2026-04-18T10:00:00Z",
        payoutDate: "2026-05-06T09:00:00Z",
      },
    ],
  },
  {
    id: "inv_2026_03",
    periodLabel: "March 2026",
    periodStart: "2026-03-01",
    periodEnd: "2026-03-31",
    totalSales: 7890,
    totalBookings: 174,
    grossRevenue: 7890,
    platformFees: 157.8,
    stripeFees: 134.1,
    refunds: 0,
    netPaidOut: 7598.1,
    payoutDestination: "Barclays business account ···4821",
    payoutDates: ["2026-04-22T09:00:00Z"],
    vatNet: 6575,
    vatAmount: 1315,
    lineItems: [],
  },
];

export const FINANCE_OVERVIEW: FinanceOverviewMetrics = {
  totalRevenue: 18420.5,
  netRevenue: 17284.12,
  platformFees: 368.41,
  stripeFees: 312.97,
  pendingPayouts: 2847.6,
  failedPayments: 3,
  refunds: 245.0,
  averageBookingValue: 42.85,
  revenueThisMonth: 4280.0,
  revenueLast30Days: 6125.5,
};

export const FINANCE_TRANSACTIONS: FinanceTransaction[] = [
  {
    id: "txn_001",
    bookingId: "bk_1042",
    date: "2026-06-12T14:22:00Z",
    parentName: "Sarah Mitchell",
    parentEmail: "sarah.mitchell@email.com",
    childName: "Oliver Mitchell",
    activityName: "Saturday Football Academy",
    venue: "Riverside Sports Centre",
    grossAmount: 45.0,
    stripeFee: 0.88,
    platformFee: 0.9,
    netAmount: 43.22,
    paymentStatus: "paid",
    payoutStatus: "pending",
  },
  {
    id: "txn_002",
    bookingId: "bk_1038",
    date: "2026-06-11T09:15:00Z",
    parentName: "James Okonkwo",
    parentEmail: "j.okonkwo@email.com",
    childName: "Amara Okonkwo",
    activityName: "Junior Tennis Camp",
    venue: "Oakwood Tennis Club",
    grossAmount: 60.0,
    stripeFee: 1.1,
    platformFee: 1.2,
    netAmount: 57.7,
    paymentStatus: "paid",
    payoutStatus: "paid_out",
  },
  {
    id: "txn_003",
    bookingId: "bk_1035",
    date: "2026-06-10T18:40:00Z",
    parentName: "Emma Clarke",
    parentEmail: "emma.clarke@email.com",
    childName: "Lily Clarke",
    activityName: "Creative Dance Workshop",
    venue: "Town Hall Studio",
    grossAmount: 35.0,
    stripeFee: 0.73,
    platformFee: 0.7,
    netAmount: 33.57,
    paymentStatus: "paid",
    payoutStatus: "paid_out",
  },
  {
    id: "txn_004",
    bookingId: "bk_1031",
    date: "2026-06-09T11:05:00Z",
    parentName: "David Hughes",
    parentEmail: "d.hughes@email.com",
    childName: "Noah Hughes",
    activityName: "Multi-Sports Holiday Club",
    venue: "Riverside Sports Centre",
    grossAmount: 85.0,
    stripeFee: 1.48,
    platformFee: 1.7,
    netAmount: 81.82,
    paymentStatus: "paid",
    payoutStatus: "in_transit",
  },
  {
    id: "txn_005",
    bookingId: "bk_1028",
    date: "2026-06-08T16:30:00Z",
    parentName: "Priya Sharma",
    parentEmail: "priya.sharma@email.com",
    childName: "Arjun Sharma",
    activityName: "Saturday Football Academy",
    venue: "Riverside Sports Centre",
    grossAmount: 45.0,
    stripeFee: 0.88,
    platformFee: 0.9,
    netAmount: 43.22,
    paymentStatus: "partially_refunded",
    payoutStatus: "paid_out",
  },
  {
    id: "txn_006",
    bookingId: "bk_1024",
    date: "2026-06-07T08:50:00Z",
    parentName: "Michael Brown",
    parentEmail: "m.brown@email.com",
    childName: "Sophie Brown",
    activityName: "Swimming Skills Level 2",
    venue: "AquaFit Pool",
    grossAmount: 40.0,
    stripeFee: 0.8,
    platformFee: 0.8,
    netAmount: 38.4,
    paymentStatus: "failed",
    payoutStatus: "held",
  },
  {
    id: "txn_007",
    bookingId: "bk_1020",
    date: "2026-06-05T13:12:00Z",
    parentName: "Laura Bennett",
    parentEmail: "laura.b@email.com",
    childName: "Ethan Bennett",
    activityName: "Junior Tennis Camp",
    venue: "Oakwood Tennis Club",
    grossAmount: 60.0,
    stripeFee: 1.1,
    platformFee: 1.2,
    netAmount: 57.7,
    paymentStatus: "paid",
    payoutStatus: "paid_out",
  },
  {
    id: "txn_008",
    bookingId: "bk_1016",
    date: "2026-06-04T10:00:00Z",
    parentName: "Chris Taylor",
    parentEmail: "c.taylor@email.com",
    childName: "Mia Taylor",
    activityName: "Creative Dance Workshop",
    venue: "Town Hall Studio",
    grossAmount: 35.0,
    stripeFee: 0.73,
    platformFee: 0.7,
    netAmount: 33.57,
    paymentStatus: "refunded",
    payoutStatus: "paid_out",
  },
];

export const PAYOUT_SUMMARY: PayoutSummary = {
  availableBalance: 1842.35,
  pendingBalance: 2847.6,
  lastPayoutDate: "2026-06-03T09:00:00Z",
  lastPayoutAmount: 3250.0,
  nextEstimatedPayoutDate: "2026-06-17T09:00:00Z",
};

export const FINANCE_PAYOUTS: FinancePayout[] = [
  {
    id: "po_004",
    date: "2026-06-03T09:00:00Z",
    amount: 3250.0,
    status: "paid_out",
    reference: "po_1NqK8x2mZ4",
    linkedTransactionIds: ["txn_002", "txn_003", "txn_007"],
  },
  {
    id: "po_003",
    date: "2026-05-20T09:00:00Z",
    amount: 2890.5,
    status: "paid_out",
    reference: "po_1NqJ4v8kL2",
    linkedTransactionIds: [],
  },
  {
    id: "po_002",
    date: "2026-05-06T09:00:00Z",
    amount: 3120.0,
    status: "paid_out",
    reference: "po_1NqH2t6jK0",
    linkedTransactionIds: [],
  },
  {
    id: "po_001",
    date: "2026-04-22T09:00:00Z",
    amount: 2755.25,
    status: "paid_out",
    reference: "po_1NqF0r4hI8",
    linkedTransactionIds: [],
  },
];

export const FAILED_PAYMENTS: FailedPayment[] = [
  {
    id: "fp_001",
    bookingId: "bk_1024",
    parentName: "Michael Brown",
    parentEmail: "m.brown@email.com",
    activityName: "Swimming Skills Level 2",
    amount: 40.0,
    reason: "Card declined — insufficient funds",
    lastAttempted: "2026-06-07T08:50:00Z",
    retryStatus: "ready",
    actionNeeded: "Retry payment or contact parent",
  },
  {
    id: "fp_002",
    bookingId: "bk_1019",
    parentName: "Helen Wright",
    parentEmail: "h.wright@email.com",
    activityName: "Saturday Football Academy",
    amount: 45.0,
    reason: "Authentication required — 3D Secure failed",
    lastAttempted: "2026-06-06T17:20:00Z",
    retryStatus: "manual_required",
    actionNeeded: "Ask parent to complete bank verification",
  },
  {
    id: "fp_003",
    bookingId: "bk_1014",
    parentName: "Tom Anderson",
    parentEmail: "t.anderson@email.com",
    activityName: "Multi-Sports Holiday Club",
    amount: 85.0,
    reason: "Expired card",
    lastAttempted: "2026-06-04T12:05:00Z",
    retryStatus: "exhausted",
    actionNeeded: "Request updated payment method",
  },
];

export const FINANCE_REFUNDS: FinanceRefund[] = [
  {
    id: "rf_002",
    date: "2026-06-08T10:30:00Z",
    customerName: "Chris Taylor",
    customerEmail: "c.taylor@email.com",
    bookingId: "bk_1016",
    bookingReference: "BK-1016",
    activityName: "Creative Dance Workshop",
    refundAmount: 35.0,
    reason: "Session cancelled by club",
    status: "completed",
  },
  {
    id: "rf_001",
    date: "2026-06-09T15:45:00Z",
    customerName: "Priya Sharma",
    customerEmail: "priya.sharma@email.com",
    bookingId: "bk_1028",
    bookingReference: "BK-1028",
    activityName: "Saturday Football Academy",
    refundAmount: 22.5,
    reason: "Partial refund — one session missed",
    status: "completed",
  },
  {
    id: "rf_003",
    date: "2026-06-11T09:00:00Z",
    customerName: "Rachel Green",
    customerEmail: "r.green@email.com",
    bookingId: "bk_1030",
    bookingReference: "BK-1030",
    activityName: "Junior Tennis Camp",
    refundAmount: 60.0,
    reason: "Duplicate booking",
    status: "pending",
  },
];

export const FINANCE_REPORTS: FinanceReport[] = [
  {
    id: "revenue",
    title: "Revenue report",
    description: "Gross and net revenue with VAT breakdown for a selected period.",
    format: "CSV",
    lastGenerated: "2026-06-01T08:00:00Z",
  },
  {
    id: "activity_revenue",
    title: "Activity revenue report",
    description: "Revenue broken down by activity and session type.",
    format: "CSV",
    lastGenerated: "2026-06-01T08:00:00Z",
  },
  {
    id: "venue_revenue",
    title: "Venue revenue report",
    description: "Revenue performance grouped by venue location.",
    format: "CSV",
    lastGenerated: null,
  },
  {
    id: "customer_spend",
    title: "Customer spend report",
    description: "Total spend and booking frequency per parent account.",
    format: "CSV",
    lastGenerated: "2026-05-15T08:00:00Z",
  },
  {
    id: "fee",
    title: "Fee report",
    description: "Platform and Stripe fees collected per transaction, with VAT where applicable.",
    format: "CSV",
    lastGenerated: null,
  },
  {
    id: "payout_reconciliation",
    title: "Payout reconciliation report",
    description: "Match payouts to linked transactions and net amounts.",
    format: "CSV",
    lastGenerated: "2026-06-03T10:00:00Z",
  },
  {
    id: "refund",
    title: "Refund report",
    description: "All refunds issued with reason codes and status.",
    format: "CSV",
    lastGenerated: null,
  },
];

export const BOOKKEEPING_SYNC_ITEMS = [
  "Sales",
  "Bookings",
  "Refunds",
  "VAT",
  "Platform fees",
  "Stripe fees",
  "Payouts",
  "Monthly invoices",
] as const;

export const ACCOUNTING_INTEGRATIONS = [
  {
    id: "quickbooks",
    name: "QuickBooks",
    description:
      "Sync sales, bookings, VAT, fees, refunds, payouts, and monthly invoices into QuickBooks.",
    status: "not_connected",
    syncItems: [...BOOKKEEPING_SYNC_ITEMS],
  },
  {
    id: "freeagent",
    name: "FreeAgent",
    description:
      "Send itemised sales, VAT, platform fees, Stripe fees, and monthly invoices to FreeAgent.",
    status: "not_connected",
    syncItems: [...BOOKKEEPING_SYNC_ITEMS],
  },
  {
    id: "xero",
    name: "Xero",
    description:
      "Connect Xero to receive bookings, VAT lines, fee deductions, and payout reconciliation entries.",
    status: "not_connected",
    syncItems: [...BOOKKEEPING_SYNC_ITEMS],
  },
  {
    id: "sage",
    name: "Sage",
    description:
      "Export sales, refunds, VAT, and monthly invoice data into Sage for club bookkeeping.",
    status: "not_connected",
    syncItems: [...BOOKKEEPING_SYNC_ITEMS],
  },
] as const satisfies readonly AccountingIntegration[];
