export const FINANCE_TABS = [
  { id: "overview", label: "Overview" },
  { id: "transactions", label: "Transactions" },
  { id: "payouts", label: "Payouts" },
  { id: "failed-payments", label: "Failed payments" },
  { id: "refunds", label: "Refunds" },
  { id: "fees", label: "Fee handling" },
  { id: "stripe", label: "Stripe" },
  { id: "payment-providers", label: "Payment providers" },
  { id: "invoices", label: "Invoices" },
  { id: "vat", label: "VAT" },
  { id: "accountant", label: "Accountant" },
  { id: "integrations", label: "Bookkeeping" },
  { id: "reports", label: "Reports" },
] as const;
