import type { ChatState } from "./types";

export const MOCK_CHAT_STATE: ChatState = {
  conversations: [
    {
      id: "conv_001",
      type: "public",
      status: "open",
      priority: "normal",
      handledBy: "human",
      aiAssistantEnabled: false,
      contactName: "Jenny Morrison",
      contactEmail: "jenny.m@example.com",
      userType: "visitor",
      subject: "How do I list my club?",
      lastMessagePreview: "We run a gymnastics club in York — how do we join?",
      lastMessageAt: "2026-06-13T15:30:00Z",
      createdAt: "2026-06-13T15:28:00Z",
      updatedAt: "2026-06-13T15:30:00Z",
    },
    {
      id: "conv_002",
      type: "parent",
      status: "pending",
      priority: "high",
      handledBy: "hybrid",
      aiAssistantEnabled: true,
      contactName: "Helen Wright",
      contactEmail: "helen.wright@example.com",
      userType: "parent",
      bookingId: "bkg_001",
      bookingReference: "ACT-2026-00142",
      providerId: "prov_001",
      providerName: "Riverside FC Academy",
      assignedAdminId: "admin_demo_001",
      assignedAdminName: "Platform Admin",
      subject: "Booking change request",
      lastMessagePreview: "Can we move Oliver to the 10:30 slot instead?",
      lastMessageAt: "2026-06-14T09:12:00Z",
      createdAt: "2026-06-14T09:10:00Z",
      updatedAt: "2026-06-14T09:12:00Z",
    },
    {
      id: "conv_003",
      type: "provider",
      status: "open",
      priority: "urgent",
      handledBy: "human",
      aiAssistantEnabled: false,
      contactName: "Sarah Mitchell",
      contactEmail: "sarah@riversidefc.co.uk",
      userType: "provider",
      providerId: "prov_001",
      providerName: "Riverside FC Academy",
      assignedAdminId: "admin_demo_001",
      assignedAdminName: "Platform Admin",
      subject: "Stripe payout issue",
      lastMessagePreview: "Payout failed again — account shows restricted.",
      lastMessageAt: "2026-06-14T08:45:00Z",
      createdAt: "2026-06-13T17:00:00Z",
      updatedAt: "2026-06-14T08:45:00Z",
    },
    {
      id: "conv_004",
      type: "public",
      status: "resolved",
      priority: "low",
      handledBy: "ai",
      aiAssistantEnabled: true,
      contactName: "Anonymous",
      contactEmail: "info@schoolpta.org",
      userType: "visitor",
      subject: "Platform fees question",
      lastMessagePreview: "Thanks — that answers my question.",
      lastMessageAt: "2026-06-12T11:00:00Z",
      createdAt: "2026-06-12T10:30:00Z",
      updatedAt: "2026-06-12T11:00:00Z",
    },
    {
      id: "conv_005",
      type: "parent",
      status: "open",
      priority: "normal",
      handledBy: "human",
      aiAssistantEnabled: false,
      contactName: "Marcus Chen",
      contactEmail: "marcus.chen@example.com",
      userType: "parent",
      bookingId: "bkg_002",
      bookingReference: "ACT-2026-00138",
      providerId: "prov_002",
      providerName: "Little Kickers Leeds",
      subject: "Trial session confirmation",
      lastMessagePreview: "Just checking Lily is on the list for Wednesday.",
      lastMessageAt: "2026-06-13T18:20:00Z",
      createdAt: "2026-06-13T18:18:00Z",
      updatedAt: "2026-06-13T18:20:00Z",
    },
  ],
  messages: [
    {
      id: "msg_001",
      conversationId: "conv_001",
      senderType: "visitor",
      senderName: "Jenny Morrison",
      body: "We run a gymnastics club in York — how do we join Activora?",
      createdAt: "2026-06-13T15:28:00Z",
    },
    {
      id: "msg_002",
      conversationId: "conv_002",
      senderType: "parent",
      senderName: "Helen Wright",
      body: "Can we move Oliver to the 10:30 slot instead?",
      createdAt: "2026-06-14T09:10:00Z",
    },
    {
      id: "msg_003",
      conversationId: "conv_003",
      senderType: "provider",
      senderName: "Sarah Mitchell",
      body: "Payout failed again — account shows restricted.",
      createdAt: "2026-06-13T17:00:00Z",
    },
    {
      id: "msg_004",
      conversationId: "conv_004",
      senderType: "visitor",
      senderName: "Anonymous",
      body: "What percentage does Activora charge clubs?",
      createdAt: "2026-06-12T10:30:00Z",
    },
    {
      id: "msg_005",
      conversationId: "conv_004",
      senderType: "system",
      senderName: "Activora AI",
      body: "Our default platform fee is 2% on paid bookings. Clubs can see exact fees in their dashboard.",
      createdAt: "2026-06-12T10:45:00Z",
    },
    {
      id: "msg_006",
      conversationId: "conv_005",
      senderType: "parent",
      senderName: "Marcus Chen",
      body: "Just checking Lily is on the list for Wednesday.",
      createdAt: "2026-06-13T18:18:00Z",
    },
  ],
  internalNotes: [
    {
      id: "note_001",
      conversationId: "conv_003",
      authorName: "Platform Admin",
      body: "Escalated to finance — Stripe Connect restricted status.",
      createdAt: "2026-06-14T08:50:00Z",
    },
  ],
  assignments: [
    {
      id: "asgn_001",
      conversationId: "conv_002",
      adminId: "admin_demo_001",
      adminName: "Platform Admin",
      assignedAt: "2026-06-14T09:11:00Z",
    },
    {
      id: "asgn_002",
      conversationId: "conv_003",
      adminId: "admin_demo_001",
      adminName: "Platform Admin",
      assignedAt: "2026-06-13T17:05:00Z",
    },
  ],
};
