"use client";

import Link from "next/link";
import { useEffect, useMemo, useState, type FormEvent } from "react";
import { PageHeader } from "@/components/club/PageHeader";
import {
  autoGenerateReleaseDetails,
  CHANGE_AREA_LABELS,
  createRelease,
  deleteRelease,
  formSectionsToArrays,
  getAllReleases,
  getReleaseSettings,
  markReleaseInternalOnly,
  mergeReleaseIntoPrevious,
  publishRelease,
  RELEASE_CATEGORY_LABELS,
  RELEASE_STATUS_LABELS,
  releaseSectionsToForm,
  requestAutoDraft,
  syncReleasesFromServer,
  updateRelease,
  updateReleaseSettings,
  type ChangeArea,
  type Release,
  type ReleaseCategory,
} from "@/lib/releases";

const CATEGORIES: ReleaseCategory[] = [
  "feature",
  "improvement",
  "fix",
  "security",
  "performance",
];

type AdminTab = "drafts" | "published";

type ReleaseFormState = {
  title: string;
  description: string;
  type: ReleaseCategory;
  version: string;
  releaseDate: string;
  summary: string;
  features: string;
  improvements: string;
  fixes: string;
  breakingChanges: string;
  internalOnly: boolean;
};

function emptyForm(): ReleaseFormState {
  const today = new Date().toISOString().slice(0, 10);
  return {
    title: "",
    description: "",
    type: "feature",
    version: "0.5",
    releaseDate: today,
    summary: "",
    features: "",
    improvements: "",
    fixes: "",
    breakingChanges: "",
    internalOnly: false,
  };
}

function releaseToForm(release: Release): ReleaseFormState {
  const sections = releaseSectionsToForm(release);
  return {
    title: release.title,
    description: release.description,
    type: release.type,
    version: release.version,
    releaseDate: release.releaseDate.slice(0, 10),
    summary: release.summary,
    features: sections.features,
    improvements: sections.improvements,
    fixes: sections.fixes,
    breakingChanges: sections.breakingChanges,
    internalOnly: release.internalOnly,
  };
}

function formatDateTime(iso: string): string {
  return new Date(iso).toLocaleString("en-GB", {
    day: "numeric",
    month: "short",
    year: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  });
}

function formatDate(iso: string): string {
  return new Date(iso).toLocaleDateString("en-GB", {
    day: "numeric",
    month: "short",
    year: "numeric",
  });
}

const INPUT_CLASS =
  "mt-1 w-full rounded-xl border border-zinc-200 bg-white px-3 py-2 text-sm outline-none focus:border-violet-400 focus:ring-2 focus:ring-violet-100";

const LABEL_CLASS = "text-xs font-semibold text-zinc-600";

function StatusBadge({ release }: { release: Release }) {
  const styles: Record<Release["status"], string> = {
    draft: "bg-zinc-100 text-zinc-600",
    published: "bg-emerald-50 text-emerald-700",
    scheduled: "bg-violet-50 text-violet-700",
    hidden: "bg-amber-50 text-amber-800",
  };

  return (
    <div className="flex flex-wrap items-center gap-1.5">
      <span
        className={`inline-flex rounded-full px-2 py-0.5 text-xs font-semibold ${styles[release.status]}`}
      >
        {RELEASE_STATUS_LABELS[release.status]}
      </span>
      {release.autoGenerated ? (
        <span className="inline-flex rounded-full bg-sky-50 px-2 py-0.5 text-xs font-semibold text-sky-700">
          Auto
        </span>
      ) : null}
      {release.internalOnly ? (
        <span className="inline-flex rounded-full bg-amber-50 px-2 py-0.5 text-xs font-semibold text-amber-800">
          Internal
        </span>
      ) : null}
    </div>
  );
}

function AreaTags({ areas }: { areas: ChangeArea[] }) {
  if (areas.length === 0) {
    return null;
  }
  return (
    <div className="mt-1 flex flex-wrap gap-1">
      {areas.map((area) => (
        <span
          key={area}
          className="rounded-md bg-zinc-100 px-1.5 py-0.5 text-[10px] font-semibold uppercase tracking-wide text-zinc-600"
        >
          {CHANGE_AREA_LABELS[area]}
        </span>
      ))}
    </div>
  );
}

export function AdminReleasesDashboard() {
  const [releases, setReleases] = useState<Release[]>([]);
  const [autoGenerate, setAutoGenerate] = useState(true);
  const [autoDraftOnDeploy, setAutoDraftOnDeploy] = useState(true);
  const [activeTab, setActiveTab] = useState<AdminTab>("drafts");
  const [editingId, setEditingId] = useState<string | null>(null);
  const [form, setForm] = useState<ReleaseFormState>(emptyForm);
  const [showForm, setShowForm] = useState(false);
  const [syncing, setSyncing] = useState(false);
  const [generating, setGenerating] = useState(false);

  async function refresh() {
    setSyncing(true);
    const merged = await syncReleasesFromServer();
    setReleases(merged.length > 0 ? merged : getAllReleases());
    const settings = getReleaseSettings();
    setAutoGenerate(settings.autoGenerateReleaseNotes);
    setAutoDraftOnDeploy(settings.autoDraftOnDeploy);
    setSyncing(false);
  }

  useEffect(() => {
    void refresh();
  }, []);

  const drafts = useMemo(
    () =>
      releases.filter(
        (release) => release.status === "draft" && !release.mergedIntoId,
      ),
    [releases],
  );

  const published = useMemo(
    () => releases.filter((release) => release.status === "published"),
    [releases],
  );

  const visible = activeTab === "drafts" ? drafts : published;

  function updateField<K extends keyof ReleaseFormState>(
    key: K,
    value: ReleaseFormState[K],
  ) {
    setForm((current) => ({ ...current, [key]: value }));
  }

  function handleSettingsChange(
    key: "autoGenerateReleaseNotes" | "autoDraftOnDeploy",
    checked: boolean,
  ) {
    if (key === "autoGenerateReleaseNotes") {
      setAutoGenerate(checked);
    } else {
      setAutoDraftOnDeploy(checked);
    }
    updateReleaseSettings({ [key]: checked });
    void fetch("/api/admin/releases", {
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ [key]: checked }),
    });
  }

  function applyAutoGeneratedDetails() {
    if (!form.title.trim() || !form.description.trim()) {
      return;
    }
    const lines = autoGenerateReleaseDetails(
      form.title,
      form.description,
      form.type,
    );
    updateField("features", lines.join("\n"));
  }

  function openCreate() {
    setEditingId(null);
    setForm(emptyForm());
    setShowForm(true);
  }

  function openEdit(release: Release) {
    setEditingId(release.id);
    setForm(releaseToForm(release));
    setShowForm(true);
  }

  function handleSubmit(event: FormEvent) {
    event.preventDefault();
    const sections = formSectionsToArrays(form);
    const releaseDate = new Date(`${form.releaseDate}T09:00:00`).toISOString();

    if (editingId) {
      updateRelease(editingId, {
        title: form.title,
        description: form.description,
        type: form.type,
        version: form.version,
        releaseDate,
        summary: form.summary,
        internalOnly: form.internalOnly,
        ...sections,
      });
    } else {
      createRelease({
        title: form.title,
        description: form.description,
        type: form.type,
        version: form.version,
        releaseDate,
        summary: form.summary,
        internalOnly: form.internalOnly,
        status: "draft",
        ...sections,
      });
    }

    setShowForm(false);
    setEditingId(null);
    setForm(emptyForm());
    void refresh();
  }

  async function handleGenerateDraft() {
    setGenerating(true);
    await requestAutoDraft();
    await refresh();
    setActiveTab("drafts");
    setGenerating(false);
  }

  function handlePublish(id: string) {
    publishRelease(id);
    void refresh();
  }

  function handleDelete(id: string) {
    if (!confirm("Delete this release note?")) {
      return;
    }
    deleteRelease(id);
    void fetch(`/api/admin/releases/${id}`, { method: "DELETE" });
    void refresh();
  }

  function handleMerge(id: string) {
    mergeReleaseIntoPrevious(id);
    void fetch(`/api/admin/releases/${id}`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ action: "merge" }),
    });
    void refresh();
  }

  function handleInternalToggle(id: string, internalOnly: boolean) {
    markReleaseInternalOnly(id, internalOnly);
    void fetch(`/api/admin/releases/${id}`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ action: "internal", internalOnly }),
    });
    void refresh();
  }

  return (
    <div className="space-y-6">
      <PageHeader
        title="Release Notes"
        description="Review deployment drafts, edit changelog sections, and publish when ready."
        action={
          <div className="flex flex-wrap gap-2">
            <Link
              href="/updates"
              target="_blank"
              className="rounded-xl border border-zinc-200 px-4 py-2.5 text-sm font-semibold text-zinc-700 transition hover:bg-zinc-50"
            >
              View public page
            </Link>
            <button
              type="button"
              onClick={() => void handleGenerateDraft()}
              disabled={generating}
              className="rounded-xl border border-sky-200 px-4 py-2.5 text-sm font-semibold text-sky-700 transition hover:bg-sky-50 disabled:opacity-50"
            >
              {generating ? "Generating…" : "Generate draft from git"}
            </button>
            <button
              type="button"
              onClick={openCreate}
              className="rounded-xl bg-violet-600 px-4 py-2.5 text-sm font-semibold text-white transition hover:bg-violet-700"
            >
              New draft
            </button>
          </div>
        }
      />

      <div className="grid gap-4 rounded-2xl border border-zinc-200/80 bg-white p-4 shadow-sm sm:grid-cols-2">
        <label className="flex cursor-pointer items-center gap-3">
          <input
            type="checkbox"
            checked={autoGenerate}
            onChange={(event) =>
              handleSettingsChange("autoGenerateReleaseNotes", event.target.checked)
            }
            className="h-4 w-4 rounded border-zinc-300 text-violet-600 focus:ring-violet-500"
          />
          <span className="text-sm font-medium text-zinc-800">
            Auto-generate changelog bullets
          </span>
        </label>
        <label className="flex cursor-pointer items-center gap-3">
          <input
            type="checkbox"
            checked={autoDraftOnDeploy}
            onChange={(event) =>
              handleSettingsChange("autoDraftOnDeploy", event.target.checked)
            }
            className="h-4 w-4 rounded border-zinc-300 text-violet-600 focus:ring-violet-500"
          />
          <span className="text-sm font-medium text-zinc-800">
            Auto-create draft on deployment
          </span>
        </label>
      </div>

      <div className="flex flex-wrap items-center gap-2">
        <button
          type="button"
          onClick={() => setActiveTab("drafts")}
          className={`rounded-xl px-4 py-2 text-sm font-semibold ${
            activeTab === "drafts"
              ? "bg-violet-600 text-white"
              : "border border-zinc-200 text-zinc-600 hover:bg-zinc-50"
          }`}
        >
          Drafts ({drafts.length})
        </button>
        <button
          type="button"
          onClick={() => setActiveTab("published")}
          className={`rounded-xl px-4 py-2 text-sm font-semibold ${
            activeTab === "published"
              ? "bg-violet-600 text-white"
              : "border border-zinc-200 text-zinc-600 hover:bg-zinc-50"
          }`}
        >
          Published ({published.length})
        </button>
        {syncing ? (
          <span className="text-xs text-zinc-500">Syncing…</span>
        ) : null}
      </div>

      {showForm ? (
        <form
          onSubmit={handleSubmit}
          className="space-y-4 rounded-2xl border border-violet-200 bg-violet-50/30 p-5 shadow-sm"
        >
          <h2 className="text-lg font-semibold text-zinc-900">
            {editingId ? "Edit release" : "New draft"}
          </h2>
          <div className="grid gap-4 sm:grid-cols-2">
            <div>
              <label htmlFor="rel-title" className={LABEL_CLASS}>
                Title *
              </label>
              <input
                id="rel-title"
                value={form.title}
                onChange={(event) => updateField("title", event.target.value)}
                className={INPUT_CLASS}
                required
              />
            </div>
            <div>
              <label htmlFor="rel-version" className={LABEL_CLASS}>
                Version *
              </label>
              <input
                id="rel-version"
                value={form.version}
                onChange={(event) => updateField("version", event.target.value)}
                className={INPUT_CLASS}
                required
              />
            </div>
            <div>
              <label htmlFor="rel-type" className={LABEL_CLASS}>
                Primary type *
              </label>
              <select
                id="rel-type"
                value={form.type}
                onChange={(event) =>
                  updateField("type", event.target.value as ReleaseCategory)
                }
                className={INPUT_CLASS}
              >
                {CATEGORIES.map((category) => (
                  <option key={category} value={category}>
                    {RELEASE_CATEGORY_LABELS[category]}
                  </option>
                ))}
              </select>
            </div>
            <div>
              <label htmlFor="rel-date" className={LABEL_CLASS}>
                Release date
              </label>
              <input
                id="rel-date"
                type="date"
                value={form.releaseDate}
                onChange={(event) => updateField("releaseDate", event.target.value)}
                className={INPUT_CLASS}
              />
            </div>
          </div>
          <div>
            <label htmlFor="rel-desc" className={LABEL_CLASS}>
              Description *
            </label>
            <textarea
              id="rel-desc"
              value={form.description}
              onChange={(event) => updateField("description", event.target.value)}
              rows={2}
              className={INPUT_CLASS}
              required
            />
          </div>
          <div>
            <label htmlFor="rel-summary" className={LABEL_CLASS}>
              Summary *
            </label>
            <input
              id="rel-summary"
              value={form.summary}
              onChange={(event) => updateField("summary", event.target.value)}
              className={INPUT_CLASS}
              required
            />
          </div>
          <div className="grid gap-4 sm:grid-cols-2">
            {(
              [
                ["rel-features", "features", "Features added"],
                ["rel-improvements", "improvements", "Improvements"],
                ["rel-fixes", "fixes", "Fixes"],
                ["rel-breaking", "breakingChanges", "Breaking changes"],
              ] as const
            ).map(([id, key, label]) => (
              <div key={id}>
                <div className="flex items-center justify-between">
                  <label htmlFor={id} className={LABEL_CLASS}>
                    {label} (one per line)
                  </label>
                  {key === "features" && autoGenerate ? (
                    <button
                      type="button"
                      onClick={applyAutoGeneratedDetails}
                      className="text-xs font-semibold text-violet-700 hover:text-violet-900"
                    >
                      Generate from title
                    </button>
                  ) : null}
                </div>
                <textarea
                  id={id}
                  value={form[key]}
                  onChange={(event) => updateField(key, event.target.value)}
                  rows={4}
                  className={INPUT_CLASS}
                />
              </div>
            ))}
          </div>
          <label className="flex cursor-pointer items-center gap-3">
            <input
              type="checkbox"
              checked={form.internalOnly}
              onChange={(event) => updateField("internalOnly", event.target.checked)}
              className="h-4 w-4 rounded border-zinc-300 text-violet-600 focus:ring-violet-500"
            />
            <span className="text-sm font-medium text-zinc-800">
              Internal only (hidden from public /updates)
            </span>
          </label>
          <div className="flex flex-wrap gap-2">
            <button
              type="submit"
              className="rounded-xl bg-violet-600 px-5 py-2.5 text-sm font-semibold text-white hover:bg-violet-700"
            >
              {editingId ? "Save changes" : "Save draft"}
            </button>
            <button
              type="button"
              onClick={() => {
                setShowForm(false);
                setEditingId(null);
              }}
              className="rounded-xl border border-zinc-200 px-5 py-2.5 text-sm font-semibold text-zinc-700 hover:bg-zinc-50"
            >
              Cancel
            </button>
          </div>
        </form>
      ) : null}

      <div className="overflow-hidden rounded-2xl border border-zinc-200/80 bg-white shadow-sm">
        <div className="overflow-x-auto">
          <table className="w-full min-w-[960px] text-left text-sm">
            <thead className="border-b border-zinc-100 bg-zinc-50/80 text-xs font-semibold uppercase tracking-wide text-zinc-500">
              <tr>
                <th className="px-4 py-3">Version</th>
                <th className="px-4 py-3">Summary</th>
                <th className="px-4 py-3">Status</th>
                <th className="px-4 py-3">Date</th>
                <th className="px-4 py-3">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-zinc-100">
              {visible.length === 0 ? (
                <tr>
                  <td colSpan={5} className="px-4 py-8 text-center text-zinc-500">
                    {activeTab === "drafts"
                      ? "No drafts yet. Deploy changes or click “Generate draft from git”."
                      : "No published releases yet."}
                  </td>
                </tr>
              ) : (
                visible.map((release) => (
                  <tr key={release.id} className="hover:bg-violet-50/20">
                    <td className="px-4 py-3 font-semibold text-zinc-900">
                      v{release.version}
                    </td>
                    <td className="px-4 py-3">
                      <p className="font-medium text-zinc-900">{release.title}</p>
                      <p className="text-xs text-zinc-500">{release.summary}</p>
                      <AreaTags areas={release.detectedAreas} />
                    </td>
                    <td className="px-4 py-3">
                      <StatusBadge release={release} />
                    </td>
                    <td className="px-4 py-3 text-xs text-zinc-500">
                      {release.publishedAt
                        ? formatDateTime(release.publishedAt)
                        : formatDate(release.releaseDate)}
                    </td>
                    <td className="px-4 py-3">
                      <div className="flex flex-wrap gap-1.5">
                        <button
                          type="button"
                          onClick={() => openEdit(release)}
                          className="rounded-lg border border-zinc-200 px-2.5 py-1 text-xs font-semibold text-zinc-700 hover:bg-zinc-50"
                        >
                          Edit
                        </button>
                        {release.status === "draft" ? (
                          <button
                            type="button"
                            onClick={() => handlePublish(release.id)}
                            className="rounded-lg border border-emerald-200 px-2.5 py-1 text-xs font-semibold text-emerald-700 hover:bg-emerald-50"
                          >
                            Publish
                          </button>
                        ) : null}
                        <button
                          type="button"
                          onClick={() => handleMerge(release.id)}
                          className="rounded-lg border border-violet-200 px-2.5 py-1 text-xs font-semibold text-violet-700 hover:bg-violet-50"
                        >
                          Merge into previous
                        </button>
                        <button
                          type="button"
                          onClick={() =>
                            handleInternalToggle(release.id, !release.internalOnly)
                          }
                          className="rounded-lg border border-amber-200 px-2.5 py-1 text-xs font-semibold text-amber-800 hover:bg-amber-50"
                        >
                          {release.internalOnly ? "Make public" : "Internal only"}
                        </button>
                        <button
                          type="button"
                          onClick={() => handleDelete(release.id)}
                          className="rounded-lg border border-red-200 px-2.5 py-1 text-xs font-semibold text-red-700 hover:bg-red-50"
                        >
                          Delete
                        </button>
                      </div>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}
