"use client";

import Link from "next/link";
import { useEffect, useMemo, useState, type FormEvent } from "react";
import { PageHeader } from "@/components/club/PageHeader";
import {
  autoGenerateReleaseDetails,
  createRelease,
  getAllReleases,
  getReleaseSettings,
  hideRelease,
  publishRelease,
  RELEASE_CATEGORY_LABELS,
  RELEASE_NOTE_VERB_LABELS,
  RELEASE_STATUS_LABELS,
  scheduleRelease,
  updateRelease,
  updateReleaseSettings,
  type Release,
  type ReleaseCategory,
  type ReleaseStatus,
} from "@/lib/releases";

const CATEGORIES: ReleaseCategory[] = [
  "feature",
  "improvement",
  "fix",
  "security",
  "performance",
];

const STATUSES: ReleaseStatus[] = ["draft", "published", "scheduled", "hidden"];

type ReleaseFormState = {
  title: string;
  description: string;
  type: ReleaseCategory;
  version: string;
  releaseDate: string;
  summary: string;
  details: string;
  status: ReleaseStatus;
  scheduledAt: string;
};

function emptyForm(): ReleaseFormState {
  const today = new Date().toISOString().slice(0, 10);
  return {
    title: "",
    description: "",
    type: "feature",
    version: "0.5",
    releaseDate: today,
    summary: "",
    details: "",
    status: "draft",
    scheduledAt: "",
  };
}

function releaseToForm(release: Release): ReleaseFormState {
  return {
    title: release.title,
    description: release.description,
    type: release.type,
    version: release.version,
    releaseDate: release.releaseDate.slice(0, 10),
    summary: release.summary,
    details: release.details.join("\n"),
    status: release.status,
    scheduledAt: release.scheduledAt?.slice(0, 16) ?? "",
  };
}

function formatDateTime(iso: string): string {
  return new Date(iso).toLocaleString("en-GB", {
    day: "numeric",
    month: "short",
    year: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  });
}

function StatusBadge({ status }: { status: ReleaseStatus }) {
  const styles: Record<ReleaseStatus, string> = {
    draft: "bg-zinc-100 text-zinc-600",
    published: "bg-emerald-50 text-emerald-700",
    scheduled: "bg-violet-50 text-violet-700",
    hidden: "bg-amber-50 text-amber-800",
  };
  return (
    <span
      className={`inline-flex rounded-full px-2 py-0.5 text-xs font-semibold ${styles[status]}`}
    >
      {RELEASE_STATUS_LABELS[status]}
    </span>
  );
}

const INPUT_CLASS =
  "mt-1 w-full rounded-xl border border-zinc-200 bg-white px-3 py-2 text-sm outline-none focus:border-violet-400 focus:ring-2 focus:ring-violet-100";

const LABEL_CLASS = "text-xs font-semibold text-zinc-600";

export function AdminReleasesDashboard() {
  const [releases, setReleases] = useState<Release[]>([]);
  const [autoGenerate, setAutoGenerate] = useState(true);
  const [editingId, setEditingId] = useState<string | null>(null);
  const [form, setForm] = useState<ReleaseFormState>(emptyForm);
  const [showForm, setShowForm] = useState(false);
  const [statusFilter, setStatusFilter] = useState<ReleaseStatus | "all">("all");

  function refresh() {
    setReleases(getAllReleases());
    setAutoGenerate(getReleaseSettings().autoGenerateReleaseNotes);
  }

  useEffect(() => {
    refresh();
  }, []);

  const filtered = useMemo(() => {
    if (statusFilter === "all") {
      return releases;
    }
    return releases.filter((release) => release.status === statusFilter);
  }, [releases, statusFilter]);

  function updateField<K extends keyof ReleaseFormState>(
    key: K,
    value: ReleaseFormState[K],
  ) {
    setForm((current) => ({ ...current, [key]: value }));
  }

  function handleAutoGenerateToggle(checked: boolean) {
    setAutoGenerate(checked);
    updateReleaseSettings({ autoGenerateReleaseNotes: checked });
  }

  function applyAutoGeneratedDetails() {
    if (!form.title.trim() || !form.description.trim()) {
      return;
    }
    const lines = autoGenerateReleaseDetails(
      form.title,
      form.description,
      form.type,
    );
    updateField("details", lines.join("\n"));
  }

  function openCreate() {
    setEditingId(null);
    setForm(emptyForm());
    setShowForm(true);
  }

  function openEdit(release: Release) {
    setEditingId(release.id);
    setForm(releaseToForm(release));
    setShowForm(true);
  }

  function handleSubmit(event: FormEvent) {
    event.preventDefault();
    const details = form.details
      .split("\n")
      .map((line) => line.trim())
      .filter(Boolean);

    if (autoGenerate && details.length === 0 && form.title && form.description) {
      details.push(
        ...autoGenerateReleaseDetails(form.title, form.description, form.type),
      );
    }

    const releaseDate = form.scheduledAt
      ? new Date(form.scheduledAt).toISOString()
      : new Date(`${form.releaseDate}T09:00:00`).toISOString();

    if (editingId) {
      updateRelease(editingId, {
        title: form.title,
        description: form.description,
        type: form.type,
        version: form.version,
        releaseDate,
        summary: form.summary,
        details,
        status: form.status,
        scheduledAt: form.scheduledAt
          ? new Date(form.scheduledAt).toISOString()
          : null,
      });
    } else {
      createRelease({
        title: form.title,
        description: form.description,
        type: form.type,
        version: form.version,
        releaseDate,
        summary: form.summary,
        details,
        status: form.status,
        scheduledAt: form.scheduledAt
          ? new Date(form.scheduledAt).toISOString()
          : null,
      });
    }

    setShowForm(false);
    setEditingId(null);
    setForm(emptyForm());
    refresh();
  }

  function handlePublish(id: string) {
    publishRelease(id);
    refresh();
  }

  function handleSchedule(id: string) {
    const scheduledAt = prompt(
      "Schedule for (YYYY-MM-DDTHH:MM local):",
      new Date(Date.now() + 86400000).toISOString().slice(0, 16),
    );
    if (!scheduledAt) {
      return;
    }
    scheduleRelease(id, new Date(scheduledAt).toISOString());
    refresh();
  }

  function handleHide(id: string) {
    hideRelease(id);
    refresh();
  }

  return (
    <div className="space-y-6">
      <PageHeader
        title="Releases"
        description="Create, publish and manage public release notes."
        action={
          <div className="flex flex-wrap gap-2">
            <Link
              href="/updates"
              target="_blank"
              className="rounded-xl border border-zinc-200 px-4 py-2.5 text-sm font-semibold text-zinc-700 transition hover:bg-zinc-50"
            >
              View public page
            </Link>
            <button
              type="button"
              onClick={openCreate}
              className="rounded-xl bg-violet-600 px-4 py-2.5 text-sm font-semibold text-white transition hover:bg-violet-700"
            >
              Create release
            </button>
          </div>
        }
      />

      <div className="flex flex-wrap items-center justify-between gap-4 rounded-2xl border border-zinc-200/80 bg-white p-4 shadow-sm">
        <label className="flex cursor-pointer items-center gap-3">
          <input
            type="checkbox"
            checked={autoGenerate}
            onChange={(event) => handleAutoGenerateToggle(event.target.checked)}
            className="h-4 w-4 rounded border-zinc-300 text-violet-600 focus:ring-violet-500"
          />
          <span className="text-sm font-medium text-zinc-800">
            Auto generate release notes
          </span>
        </label>
        <p className="text-xs text-zinc-500">
          Format: {Object.values(RELEASE_NOTE_VERB_LABELS).join(" / ")} — e.g.{" "}
          <span className="font-mono text-zinc-700">
            Added: Club onboarding wizard
          </span>
        </p>
      </div>

      <div className="flex flex-wrap gap-2">
        <button
          type="button"
          onClick={() => setStatusFilter("all")}
          className={`rounded-xl px-3 py-2 text-xs font-semibold ${
            statusFilter === "all"
              ? "bg-violet-600 text-white"
              : "border border-zinc-200 text-zinc-600 hover:bg-zinc-50"
          }`}
        >
          All
        </button>
        {STATUSES.map((status) => (
          <button
            key={status}
            type="button"
            onClick={() => setStatusFilter(status)}
            className={`rounded-xl px-3 py-2 text-xs font-semibold ${
              statusFilter === status
                ? "bg-violet-600 text-white"
                : "border border-zinc-200 text-zinc-600 hover:bg-zinc-50"
            }`}
          >
            {RELEASE_STATUS_LABELS[status]}
          </button>
        ))}
      </div>

      {showForm ? (
        <form
          onSubmit={handleSubmit}
          className="space-y-4 rounded-2xl border border-violet-200 bg-violet-50/30 p-5 shadow-sm"
        >
          <h2 className="text-lg font-semibold text-zinc-900">
            {editingId ? "Edit release" : "New release"}
          </h2>
          <div className="grid gap-4 sm:grid-cols-2">
            <div>
              <label htmlFor="rel-title" className={LABEL_CLASS}>
                Title *
              </label>
              <input
                id="rel-title"
                value={form.title}
                onChange={(event) => updateField("title", event.target.value)}
                className={INPUT_CLASS}
                required
              />
            </div>
            <div>
              <label htmlFor="rel-version" className={LABEL_CLASS}>
                Version *
              </label>
              <input
                id="rel-version"
                value={form.version}
                onChange={(event) => updateField("version", event.target.value)}
                className={INPUT_CLASS}
                required
              />
            </div>
            <div>
              <label htmlFor="rel-type" className={LABEL_CLASS}>
                Type *
              </label>
              <select
                id="rel-type"
                value={form.type}
                onChange={(event) =>
                  updateField("type", event.target.value as ReleaseCategory)
                }
                className={INPUT_CLASS}
              >
                {CATEGORIES.map((category) => (
                  <option key={category} value={category}>
                    {RELEASE_CATEGORY_LABELS[category]}
                  </option>
                ))}
              </select>
            </div>
            <div>
              <label htmlFor="rel-status" className={LABEL_CLASS}>
                Status
              </label>
              <select
                id="rel-status"
                value={form.status}
                onChange={(event) =>
                  updateField("status", event.target.value as ReleaseStatus)
                }
                className={INPUT_CLASS}
              >
                {STATUSES.map((status) => (
                  <option key={status} value={status}>
                    {RELEASE_STATUS_LABELS[status]}
                  </option>
                ))}
              </select>
            </div>
          </div>
          <div>
            <label htmlFor="rel-desc" className={LABEL_CLASS}>
              Description *
            </label>
            <textarea
              id="rel-desc"
              value={form.description}
              onChange={(event) => updateField("description", event.target.value)}
              rows={2}
              className={INPUT_CLASS}
              required
            />
          </div>
          <div>
            <label htmlFor="rel-summary" className={LABEL_CLASS}>
              Summary *
            </label>
            <input
              id="rel-summary"
              value={form.summary}
              onChange={(event) => updateField("summary", event.target.value)}
              className={INPUT_CLASS}
              required
            />
          </div>
          <div>
            <div className="flex items-center justify-between">
              <label htmlFor="rel-details" className={LABEL_CLASS}>
                Details (one per line)
              </label>
              {autoGenerate ? (
                <button
                  type="button"
                  onClick={applyAutoGeneratedDetails}
                  className="text-xs font-semibold text-violet-700 hover:text-violet-900"
                >
                  Generate from title
                </button>
              ) : null}
            </div>
            <textarea
              id="rel-details"
              value={form.details}
              onChange={(event) => updateField("details", event.target.value)}
              rows={5}
              placeholder="Added: New feature&#10;Improved: Performance&#10;Fixed: Bug"
              className={INPUT_CLASS}
            />
          </div>
          <div className="grid gap-4 sm:grid-cols-2">
            <div>
              <label htmlFor="rel-date" className={LABEL_CLASS}>
                Release date
              </label>
              <input
                id="rel-date"
                type="date"
                value={form.releaseDate}
                onChange={(event) => updateField("releaseDate", event.target.value)}
                className={INPUT_CLASS}
              />
            </div>
            <div>
              <label htmlFor="rel-scheduled" className={LABEL_CLASS}>
                Scheduled at (optional)
              </label>
              <input
                id="rel-scheduled"
                type="datetime-local"
                value={form.scheduledAt}
                onChange={(event) => updateField("scheduledAt", event.target.value)}
                className={INPUT_CLASS}
              />
            </div>
          </div>
          <div className="flex flex-wrap gap-2">
            <button
              type="submit"
              className="rounded-xl bg-violet-600 px-5 py-2.5 text-sm font-semibold text-white hover:bg-violet-700"
            >
              {editingId ? "Save changes" : "Create release"}
            </button>
            <button
              type="button"
              onClick={() => {
                setShowForm(false);
                setEditingId(null);
              }}
              className="rounded-xl border border-zinc-200 px-5 py-2.5 text-sm font-semibold text-zinc-700 hover:bg-zinc-50"
            >
              Cancel
            </button>
          </div>
        </form>
      ) : null}

      <div className="overflow-hidden rounded-2xl border border-zinc-200/80 bg-white shadow-sm">
        <div className="overflow-x-auto">
          <table className="w-full min-w-[900px] text-left text-sm">
            <thead className="border-b border-zinc-100 bg-zinc-50/80 text-xs font-semibold uppercase tracking-wide text-zinc-500">
              <tr>
                <th className="px-4 py-3">Version</th>
                <th className="px-4 py-3">Title</th>
                <th className="px-4 py-3">Type</th>
                <th className="px-4 py-3">Status</th>
                <th className="px-4 py-3">Published</th>
                <th className="px-4 py-3">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-zinc-100">
              {filtered.length === 0 ? (
                <tr>
                  <td colSpan={6} className="px-4 py-8 text-center text-zinc-500">
                    No releases match this filter.
                  </td>
                </tr>
              ) : (
                filtered.map((release) => (
                  <tr key={release.id} className="hover:bg-violet-50/20">
                    <td className="px-4 py-3 font-semibold text-zinc-900">
                      v{release.version}
                    </td>
                    <td className="px-4 py-3">
                      <p className="font-medium text-zinc-900">{release.title}</p>
                      <p className="text-xs text-zinc-500">{release.summary}</p>
                    </td>
                    <td className="px-4 py-3 text-zinc-700">
                      {RELEASE_CATEGORY_LABELS[release.type]}
                    </td>
                    <td className="px-4 py-3">
                      <StatusBadge status={release.status} />
                    </td>
                    <td className="px-4 py-3 text-xs text-zinc-500">
                      {release.publishedAt
                        ? formatDateTime(release.publishedAt)
                        : release.scheduledAt
                          ? `Scheduled ${formatDateTime(release.scheduledAt)}`
                          : "—"}
                    </td>
                    <td className="px-4 py-3">
                      <div className="flex flex-wrap gap-1.5">
                        <button
                          type="button"
                          onClick={() => openEdit(release)}
                          className="rounded-lg border border-zinc-200 px-2.5 py-1 text-xs font-semibold text-zinc-700 hover:bg-zinc-50"
                        >
                          Edit
                        </button>
                        {release.status !== "published" ? (
                          <button
                            type="button"
                            onClick={() => handlePublish(release.id)}
                            className="rounded-lg border border-emerald-200 px-2.5 py-1 text-xs font-semibold text-emerald-700 hover:bg-emerald-50"
                          >
                            Publish
                          </button>
                        ) : null}
                        {release.status !== "scheduled" ? (
                          <button
                            type="button"
                            onClick={() => handleSchedule(release.id)}
                            className="rounded-lg border border-violet-200 px-2.5 py-1 text-xs font-semibold text-violet-700 hover:bg-violet-50"
                          >
                            Schedule
                          </button>
                        ) : null}
                        {release.status !== "hidden" ? (
                          <button
                            type="button"
                            onClick={() => handleHide(release.id)}
                            className="rounded-lg border border-amber-200 px-2.5 py-1 text-xs font-semibold text-amber-800 hover:bg-amber-50"
                          >
                            Hide
                          </button>
                        ) : null}
                      </div>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}
