import type { SupportState } from "./types";

export const SUPPORT_THREADS_KEY = "activora-support-threads";
export const SUPPORT_MESSAGES_KEY = "activora-support-messages";
export const SUPPORT_ASSIGNMENTS_KEY = "activora-support-assignments";

export const SUPPORT_AGENT_NAME = "Chima";
export const SUPPORT_AGENT_TITLE = "Head of Support";
export const SUPPORT_AGENT_AVATAR =
  "https://i.pravatar.cc/150?u=chima-activora-support";

export const SEED_SUPPORT_STATE: SupportState = {
  threads: [
    {
      id: "thread_seed_001",
      context: "club_onboarding",
      support_mode: "hybrid",
      message_type: "support",
      status: "assigned",
      subject: "Club onboarding help",
      icon: "🟢",
      contact_name: "Sarah Mitchell",
      contact_email: "sarah@riversidefc.co.uk",
      last_message_preview: "How do I add a second venue?",
      last_message_at: "2026-06-13T14:22:00Z",
      created_at: "2026-06-12T09:15:00Z",
      updated_at: "2026-06-13T14:22:00Z",
    },
    {
      id: "thread_seed_002",
      context: "parent",
      support_mode: "hybrid",
      message_type: "bookings",
      status: "resolved",
      subject: "Session booking",
      icon: "🤖",
      contact_name: "Helen Wright",
      contact_email: "helen.wright@example.com",
      last_message_preview: "Thanks — booking moved to Saturday.",
      last_message_at: "2026-06-11T16:45:00Z",
      created_at: "2026-06-11T15:30:00Z",
      updated_at: "2026-06-11T16:45:00Z",
    },
    {
      id: "thread_seed_003",
      context: "club_signed_in",
      support_mode: "human",
      message_type: "payments",
      status: "waiting",
      subject: "Payment issue",
      icon: "👤",
      contact_name: "James Porter",
      contact_email: "james@yorkgym.co.uk",
      last_message_preview: "Stripe payout still pending after 5 days.",
      last_message_at: "2026-06-13T11:08:00Z",
      created_at: "2026-06-13T10:55:00Z",
      updated_at: "2026-06-13T11:08:00Z",
    },
    {
      id: "thread_seed_004",
      context: "public",
      support_mode: "hybrid",
      message_type: "general",
      status: "resolved",
      subject: "Listing my club",
      icon: "🟢",
      contact_name: "Jenny Morrison",
      contact_email: "jenny.m@example.com",
      last_message_preview: "We'll send onboarding details shortly.",
      last_message_at: "2026-06-10T09:20:00Z",
      created_at: "2026-06-10T09:00:00Z",
      updated_at: "2026-06-10T09:20:00Z",
      archived: true,
    },
  ],
  messages: [
    {
      id: "msg_seed_001",
      thread_id: "thread_seed_001",
      sender_type: "user",
      sender_name: "Sarah Mitchell",
      body: "I'm stuck on the venues step — can I add more than one?",
      message_type: "support",
      created_at: "2026-06-12T09:15:00Z",
    },
    {
      id: "msg_seed_002",
      thread_id: "thread_seed_001",
      sender_type: "ai",
      sender_name: "Activora AI",
      body: "Yes! Click 'Add venue' on step 6 to add multiple locations. Each venue can be linked to different sessions.",
      message_type: "support",
      created_at: "2026-06-12T09:16:00Z",
    },
    {
      id: "msg_seed_003",
      thread_id: "thread_seed_001",
      sender_type: "user",
      sender_name: "Sarah Mitchell",
      body: "How do I add a second venue?",
      message_type: "support",
      created_at: "2026-06-13T14:22:00Z",
    },
    {
      id: "msg_seed_004",
      thread_id: "thread_seed_002",
      sender_type: "user",
      sender_name: "Helen Wright",
      body: "Can we move Oliver's football session to Saturday morning?",
      message_type: "bookings",
      created_at: "2026-06-11T15:30:00Z",
    },
    {
      id: "msg_seed_005",
      thread_id: "thread_seed_002",
      sender_type: "ai",
      sender_name: "Activora AI",
      body: "I've found an available slot Saturday 10:00 at Riverside FC. Shall I request the change from the club?",
      message_type: "bookings",
      created_at: "2026-06-11T15:31:00Z",
    },
    {
      id: "msg_seed_006",
      thread_id: "thread_seed_003",
      sender_type: "user",
      sender_name: "James Porter",
      body: "My Stripe payout from last week is still showing as pending. Reference PAY-2026-0891.",
      message_type: "payments",
      created_at: "2026-06-13T10:55:00Z",
    },
    {
      id: "msg_seed_007",
      thread_id: "thread_seed_004",
      sender_type: "user",
      sender_name: "Jenny Morrison",
      body: "We run a gymnastics club in York — how do we join Activora?",
      message_type: "general",
      created_at: "2026-06-10T09:00:00Z",
    },
  ],
  assignments: [
    {
      id: "assign_seed_001",
      thread_id: "thread_seed_001",
      assignee_id: "chima",
      assignee_name: "Chima",
      assigned_at: "2026-06-12T10:00:00Z",
    },
  ],
};
