import {
  buildChangelogSections,
  classifyChangeType,
  detectAreasFromFiles,
  suggestAreaLabels,
} from "./detect-changes";
import type { Release, ReleaseCategory, ReleaseDraftSuggestion } from "./types";
import { CHANGE_AREA_LABELS, CURRENT_VERSION } from "./types";
import { getLatestVersion, suggestNextVersion } from "./version";

function releaseCategoryFromChangeType(
  changeType: ReturnType<typeof classifyChangeType>,
): ReleaseCategory {
  switch (changeType) {
    case "fix":
      return "fix";
    case "ui_tweak":
      return "ui";
    case "major":
    case "feature":
    default:
      return "feature";
  }
}

function buildTitle(version: string, areas: ReturnType<typeof detectAreasFromFiles>): string {
  const primary = areas.filter((area) => area !== "other").slice(0, 2);
  const labels = primary.map((area) => CHANGE_AREA_LABELS[area]).join(" & ");
  if (labels) {
    return `Activora ${version} — ${labels}`;
  }
  return `Activora ${version} — Platform update`;
}

function buildSummary(
  changeType: ReturnType<typeof classifyChangeType>,
  areas: ReturnType<typeof detectAreasFromFiles>,
): string {
  const labels = suggestAreaLabels(areas.filter((area) => area !== "other"));
  const areaText = labels.length > 0 ? labels.join(", ") : "the platform";

  switch (changeType) {
    case "fix":
      return `Bug fixes and stability improvements across ${areaText}.`;
    case "ui_tweak":
      return `UI polish and usability tweaks for ${areaText}.`;
    case "major":
      return `Notable platform changes across ${areaText}, including breaking updates.`;
    case "feature":
    default:
      return `New improvements shipped for ${areaText}.`;
  }
}

export function buildReleaseDraftSuggestion(input: {
  changedFiles: string[];
  commitMessages?: string[];
  baseVersion?: string;
  existingVersions?: string[];
}): ReleaseDraftSuggestion {
  const changedFiles = input.changedFiles.filter(Boolean);
  const commitMessages = input.commitMessages ?? [];
  const detectedAreas = detectAreasFromFiles(changedFiles);
  const changeType = classifyChangeType(changedFiles, commitMessages);
  const latest =
    input.existingVersions && input.existingVersions.length > 0
      ? getLatestVersion(input.existingVersions)
      : (input.baseVersion ?? CURRENT_VERSION);
  const version = suggestNextVersion(latest, changeType);
  const sections = buildChangelogSections(detectedAreas, changedFiles, commitMessages);
  const type = releaseCategoryFromChangeType(changeType);

  return {
    version,
    changeType,
    title: buildTitle(version, detectedAreas),
    summary: buildSummary(changeType, detectedAreas),
    description: `Auto-generated draft from ${changedFiles.length} changed file(s) in ${detectedAreas.map((area) => CHANGE_AREA_LABELS[area]).join(", ")}.`,
    type,
    features: sections.features,
    improvements: sections.improvements,
    fixes: sections.fixes,
    breakingChanges: sections.breakingChanges,
    detectedAreas,
    changedFiles,
  };
}

export function suggestionToCreateInput(
  suggestion: ReleaseDraftSuggestion,
  releaseDate = new Date().toISOString(),
) {
  const details = combineReleaseDetails({
    features: suggestion.features,
    improvements: suggestion.improvements,
    fixes: suggestion.fixes,
    breakingChanges: suggestion.breakingChanges,
    details: [],
  });

  return {
    title: suggestion.title,
    description: suggestion.description,
    type: suggestion.type,
    version: suggestion.version,
    releaseDate,
    summary: suggestion.summary,
    details,
    features: suggestion.features,
    improvements: suggestion.improvements,
    fixes: suggestion.fixes,
    breakingChanges: suggestion.breakingChanges,
    status: "draft" as const,
    autoGenerated: true,
    detectedAreas: suggestion.detectedAreas,
  };
}

export function combineReleaseDetails(release: Pick<
  Release,
  "features" | "improvements" | "fixes" | "breakingChanges" | "details"
>): string[] {
  if (release.details.length > 0) {
    return release.details;
  }

  const lines: string[] = [];
  for (const item of release.features) {
    lines.push(`Added: ${item}`);
  }
  for (const item of release.improvements) {
    lines.push(`Improved: ${item}`);
  }
  for (const item of release.fixes) {
    lines.push(`Fixed: ${item}`);
  }
  for (const item of release.breakingChanges) {
    lines.push(`Breaking: ${item}`);
  }
  return lines;
}

export function normalizeReleaseStatus(
  status: string | undefined,
  internalOnly?: boolean,
): Release["status"] {
  if (internalOnly || status === "hidden" || status === "internal") {
    return "internal";
  }
  if (status === "published") {
    return "published";
  }
  if (status === "scheduled") {
    return "draft";
  }
  return "draft";
}

export function normalizeRelease(release: Release): Release {
  const status = normalizeReleaseStatus(release.status, release.internalOnly);
  const details =
    release.details.length > 0
      ? release.details
      : combineReleaseDetails(release);

  return {
    ...release,
    type:
      (release.type as string) === "improvement" ? "ui" : release.type,
    features: release.features ?? [],
    improvements: release.improvements ?? [],
    fixes: release.fixes ?? [],
    breakingChanges: release.breakingChanges ?? [],
    status,
    autoGenerated: release.autoGenerated ?? false,
    detectedAreas: release.detectedAreas ?? [],
    mergedIntoId: release.mergedIntoId ?? null,
    details,
  };
}
