import { execSync } from "node:child_process";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import {
  DEFAULT_RELEASE_SETTINGS,
  RELEASE_SETTINGS_KEY,
  RELEASES_KEY,
  SEED_RELEASES,
} from "./defaults";
import {
  buildReleaseDraftSuggestion,
  normalizeRelease,
  suggestionToCreateInput,
} from "./generate-draft";
import type {
  CreateReleaseInput,
  Release,
  ReleaseSettings,
  UpdateReleaseInput,
} from "./types";

const DATA_DIR = path.join(process.cwd(), ".data");
const RELEASES_FILE = path.join(DATA_DIR, "releases.json");
const SETTINGS_FILE = path.join(DATA_DIR, "releases-settings.json");

function createId(prefix: string): string {
  return `${prefix}_${crypto.randomUUID().slice(0, 8)}`;
}

function nowIso(): string {
  return new Date().toISOString();
}

async function ensureDataDir(): Promise<void> {
  await mkdir(DATA_DIR, { recursive: true });
}

async function readJsonFile<T>(filePath: string, fallback: T): Promise<T> {
  try {
    const raw = await readFile(filePath, "utf8");
    return JSON.parse(raw) as T;
  } catch {
    return fallback;
  }
}

async function writeJsonFile<T>(filePath: string, value: T): Promise<void> {
  await ensureDataDir();
  await writeFile(filePath, `${JSON.stringify(value, null, 2)}\n`, "utf8");
}

async function loadReleases(): Promise<Release[]> {
  const stored = await readJsonFile<Release[]>(RELEASES_FILE, []);
  if (stored.length === 0) {
    const seeded = SEED_RELEASES.map(normalizeRelease);
    await writeJsonFile(RELEASES_FILE, seeded);
    return seeded;
  }
  return stored.map(normalizeRelease);
}

async function saveReleases(releases: Release[]): Promise<void> {
  await writeJsonFile(RELEASES_FILE, releases);
}

export async function getServerReleaseSettings(): Promise<ReleaseSettings> {
  const settings = await readJsonFile<ReleaseSettings>(
    SETTINGS_FILE,
    DEFAULT_RELEASE_SETTINGS,
  );
  return { ...DEFAULT_RELEASE_SETTINGS, ...settings };
}

export async function updateServerReleaseSettings(
  updates: Partial<ReleaseSettings>,
): Promise<ReleaseSettings> {
  const current = await getServerReleaseSettings();
  const next = { ...current, ...updates };
  await writeJsonFile(SETTINGS_FILE, next);
  return next;
}

export async function getServerReleases(): Promise<Release[]> {
  const releases = await loadReleases();
  return [...releases].sort(
    (a, b) => new Date(b.releaseDate).getTime() - new Date(a.releaseDate).getTime(),
  );
}

export async function getServerReleaseById(id: string): Promise<Release | null> {
  const releases = await loadReleases();
  return releases.find((release) => release.id === id) ?? null;
}

export async function createServerRelease(input: CreateReleaseInput): Promise<Release> {
  const releases = await loadReleases();
  const now = nowIso();
  const status = input.status ?? "draft";
  const release = normalizeRelease({
    id: createId("rel"),
    title: input.title.trim(),
    description: input.description.trim(),
    type: input.type,
    version: input.version.trim(),
    releaseDate: input.releaseDate,
    summary: input.summary.trim(),
    details: (input.details ?? []).map((line) => line.trim()).filter(Boolean),
    features: input.features ?? [],
    improvements: input.improvements ?? [],
    fixes: input.fixes ?? [],
    breakingChanges: input.breakingChanges ?? [],
    status,
    autoGenerated: input.autoGenerated ?? false,
    detectedAreas: input.detectedAreas ?? [],
    mergedIntoId: null,
    scheduledAt: input.scheduledAt ?? null,
    publishedAt: status === "published" ? now : null,
    createdAt: now,
    updatedAt: now,
  });

  await saveReleases([release, ...releases]);
  return release;
}

export async function updateServerRelease(
  id: string,
  input: UpdateReleaseInput,
): Promise<Release | null> {
  const releases = await loadReleases();
  const index = releases.findIndex((release) => release.id === id);
  if (index === -1) {
    return null;
  }

  const current = releases[index];
  const updated = normalizeRelease({
    ...current,
    ...input,
    title: input.title?.trim() ?? current.title,
    description: input.description?.trim() ?? current.description,
    version: input.version?.trim() ?? current.version,
    summary: input.summary?.trim() ?? current.summary,
    details: input.details
      ? input.details.map((line) => line.trim()).filter(Boolean)
      : current.details,
    features: input.features ?? current.features,
    improvements: input.improvements ?? current.improvements,
    fixes: input.fixes ?? current.fixes,
    breakingChanges: input.breakingChanges ?? current.breakingChanges,
    updatedAt: nowIso(),
  });

  releases[index] = updated;
  await saveReleases(releases);
  return updated;
}

export async function deleteServerRelease(id: string): Promise<boolean> {
  const releases = await loadReleases();
  const filtered = releases.filter((release) => release.id !== id);
  if (filtered.length === releases.length) {
    return false;
  }
  await saveReleases(filtered);
  return true;
}

export async function mergeServerReleaseIntoPrevious(id: string): Promise<Release | null> {
  const releases = await loadReleases();
  const sourceIndex = releases.findIndex((release) => release.id === id);
  if (sourceIndex === -1) {
    return null;
  }

  const source = releases[sourceIndex];
  const target = releases.find(
    (release) =>
      release.id !== id &&
      !release.mergedIntoId &&
      new Date(release.createdAt).getTime() < new Date(source.createdAt).getTime(),
  );

  if (!target) {
    return null;
  }

  const targetIndex = releases.findIndex((release) => release.id === target.id);
  const mergedTarget = normalizeRelease({
    ...target,
    features: [...target.features, ...source.features],
    improvements: [...target.improvements, ...source.improvements],
    fixes: [...target.fixes, ...source.fixes],
    breakingChanges: [...target.breakingChanges, ...source.breakingChanges],
    details: [...target.details, ...source.details],
    detectedAreas: [...new Set([...target.detectedAreas, ...source.detectedAreas])],
    updatedAt: nowIso(),
  });

  const mergedSource = normalizeRelease({
    ...source,
    status: "internal",
    mergedIntoId: target.id,
    updatedAt: nowIso(),
  });

  releases[targetIndex] = mergedTarget;
  releases[sourceIndex] = mergedSource;
  await saveReleases(releases);
  return mergedTarget;
}

export function getGitChangedFiles(baseRef?: string): string[] {
  const ref = baseRef ?? process.env.RELEASE_DIFF_BASE ?? "HEAD~1";
  try {
    const output = execSync(`git diff --name-only ${ref} HEAD`, {
      encoding: "utf8",
      stdio: ["ignore", "pipe", "ignore"],
    });
    return output
      .split("\n")
      .map((line) => line.trim())
      .filter(Boolean);
  } catch {
    try {
      const output = execSync("git diff --name-only --cached", {
        encoding: "utf8",
        stdio: ["ignore", "pipe", "ignore"],
      });
      return output
        .split("\n")
        .map((line) => line.trim())
        .filter(Boolean);
    } catch {
      return [];
    }
  }
}

export function getGitCommitMessages(baseRef?: string): string[] {
  const ref = baseRef ?? process.env.RELEASE_DIFF_BASE ?? "HEAD~1";
  try {
    const output = execSync(`git log ${ref}..HEAD --pretty=format:%s`, {
      encoding: "utf8",
      stdio: ["ignore", "pipe", "ignore"],
    });
    return output
      .split("\n")
      .map((line) => line.trim())
      .filter(Boolean);
  } catch {
    return [];
  }
}

export async function generateServerReleaseDraft(baseRef?: string): Promise<Release | null> {
  const settings = await getServerReleaseSettings();
  if (!settings.autoDraftOnDeploy && !settings.autoGenerateReleaseNotes) {
    return null;
  }

  const changedFiles = getGitChangedFiles(baseRef);
  if (changedFiles.length === 0) {
    return null;
  }

  const releases = await getServerReleases();
  const existingVersions = releases.map((release) => release.version);
  const suggestion = buildReleaseDraftSuggestion({
    changedFiles,
    commitMessages: getGitCommitMessages(baseRef),
    existingVersions,
  });

  const duplicate = releases.find(
    (release) =>
      release.status === "draft" &&
      release.autoGenerated &&
      release.version === suggestion.version,
  );
  if (duplicate) {
    return duplicate;
  }

  return createServerRelease(suggestionToCreateInput(suggestion));
}

/** Keys exported for client localStorage parity. */
export { RELEASES_KEY, RELEASE_SETTINGS_KEY };
