import {
  DEFAULT_RELEASE_SETTINGS,
  RELEASE_SETTINGS_KEY,
  RELEASES_KEY,
  SEED_RELEASES,
} from "./defaults";
import { combineReleaseDetails, normalizeRelease } from "./generate-draft";
import type {
  CreateReleaseInput,
  Release,
  ReleaseNoteVerb,
  ReleaseSettings,
  ReleaseStatus,
  UpdateReleaseInput,
} from "./types";
import { RELEASE_NOTE_VERB_LABELS } from "./types";

function isBrowser(): boolean {
  return typeof window !== "undefined";
}

function createId(prefix: string): string {
  return `${prefix}_${crypto.randomUUID().slice(0, 8)}`;
}

function nowIso(): string {
  return new Date().toISOString();
}

function readJson<T>(key: string, fallback: T): T {
  if (!isBrowser()) {
    return fallback;
  }
  try {
    const raw = localStorage.getItem(key);
    if (!raw) {
      return fallback;
    }
    return JSON.parse(raw) as T;
  } catch {
    return fallback;
  }
}

function writeJson<T>(key: string, value: T): void {
  if (!isBrowser()) {
    return;
  }
  localStorage.setItem(key, JSON.stringify(value));
}

function ensureSeeded(): void {
  if (!isBrowser()) {
    return;
  }
  if (!localStorage.getItem(RELEASES_KEY)) {
    writeJson(RELEASES_KEY, SEED_RELEASES);
    writeJson(RELEASE_SETTINGS_KEY, DEFAULT_RELEASE_SETTINGS);
  }
}

function sortReleases(releases: Release[]): Release[] {
  return [...releases]
    .map(normalizeRelease)
    .sort(
      (a, b) =>
        new Date(b.releaseDate).getTime() - new Date(a.releaseDate).getTime(),
    );
}

export function getReleaseSettings(): ReleaseSettings {
  ensureSeeded();
  return readJson(RELEASE_SETTINGS_KEY, DEFAULT_RELEASE_SETTINGS);
}

export function updateReleaseSettings(
  updates: Partial<ReleaseSettings>,
): ReleaseSettings {
  ensureSeeded();
  const current = getReleaseSettings();
  const updated = { ...current, ...updates };
  writeJson(RELEASE_SETTINGS_KEY, updated);
  return updated;
}

export function getAllReleases(): Release[] {
  ensureSeeded();
  const releases = readJson<Release[]>(RELEASES_KEY, []);
  return sortReleases(releases);
}

export function getPublishedReleases(): Release[] {
  return getAllReleases().filter((release) => release.status === "published");
}

export function getDraftReleases(): Release[] {
  return getAllReleases().filter(
    (release) => release.status === "draft" && !release.mergedIntoId,
  );
}

export function getLatestPublishedReleases(limit = 3): Release[] {
  return getPublishedReleases().slice(0, limit);
}

export function getReleaseById(id: string): Release | null {
  return getAllReleases().find((release) => release.id === id) ?? null;
}

export function createRelease(input: CreateReleaseInput): Release {
  ensureSeeded();
  const releases = readJson<Release[]>(RELEASES_KEY, []);
  const now = nowIso();
  const status = input.status ?? "draft";
  const release = normalizeRelease({
    id: createId("rel"),
    title: input.title.trim(),
    description: input.description.trim(),
    type: input.type,
    version: input.version.trim(),
    releaseDate: input.releaseDate,
    summary: input.summary.trim(),
    details: (input.details ?? []).map((line) => line.trim()).filter(Boolean),
    features: input.features ?? [],
    improvements: input.improvements ?? [],
    fixes: input.fixes ?? [],
    breakingChanges: input.breakingChanges ?? [],
    status,
    autoGenerated: input.autoGenerated ?? false,
    detectedAreas: input.detectedAreas ?? [],
    mergedIntoId: null,
    scheduledAt: input.scheduledAt ?? null,
    publishedAt: status === "published" ? now : null,
    createdAt: now,
    updatedAt: now,
  });
  writeJson(RELEASES_KEY, [release, ...releases]);
  return release;
}

export function updateRelease(
  id: string,
  input: UpdateReleaseInput,
): Release | null {
  ensureSeeded();
  const releases = readJson<Release[]>(RELEASES_KEY, []);
  const index = releases.findIndex((release) => release.id === id);
  if (index === -1) {
    return null;
  }
  const current = releases[index];
  const updated = normalizeRelease({
    ...current,
    ...input,
    title: input.title?.trim() ?? current.title,
    description: input.description?.trim() ?? current.description,
    version: input.version?.trim() ?? current.version,
    summary: input.summary?.trim() ?? current.summary,
    details: input.details
      ? input.details.map((line) => line.trim()).filter(Boolean)
      : current.details,
    features: input.features ?? current.features,
    improvements: input.improvements ?? current.improvements,
    fixes: input.fixes ?? current.fixes,
    breakingChanges: input.breakingChanges ?? current.breakingChanges,
    updatedAt: nowIso(),
  });
  releases[index] = updated;
  writeJson(RELEASES_KEY, releases);
  return updated;
}

export function publishRelease(id: string): Release | null {
  return updateRelease(id, {
    status: "published",
    publishedAt: nowIso(),
    releaseDate: nowIso(),
  });
}

export function unpublishRelease(id: string): Release | null {
  return updateRelease(id, {
    status: "draft",
    publishedAt: null,
  });
}

export function markReleaseInternal(id: string): Release | null {
  return updateRelease(id, { status: "internal", publishedAt: null });
}

export function scheduleRelease(id: string, scheduledAt: string): Release | null {
  return updateRelease(id, {
    status: "draft",
    scheduledAt,
    releaseDate: scheduledAt,
  });
}

export function hideRelease(id: string): Release | null {
  return markReleaseInternal(id);
}

/** @deprecated Use `markReleaseInternal` */
export function markReleaseInternalOnly(id: string): Release | null {
  return markReleaseInternal(id);
}

export function deleteRelease(id: string): boolean {
  ensureSeeded();
  const releases = readJson<Release[]>(RELEASES_KEY, []);
  const filtered = releases.filter((release) => release.id !== id);
  if (filtered.length === releases.length) {
    return false;
  }
  writeJson(RELEASES_KEY, filtered);
  return true;
}

export function mergeReleaseIntoPrevious(id: string): Release | null {
  ensureSeeded();
  const releases = readJson<Release[]>(RELEASES_KEY, []);
  const sourceIndex = releases.findIndex((release) => release.id === id);
  if (sourceIndex === -1) {
    return null;
  }

  const source = normalizeRelease(releases[sourceIndex]);
  const target = sortReleases(releases).find(
    (release) =>
      release.id !== id &&
      !release.mergedIntoId &&
      new Date(release.createdAt).getTime() < new Date(source.createdAt).getTime(),
  );

  if (!target) {
    return null;
  }

  const targetIndex = releases.findIndex((release) => release.id === target.id);
  const mergedTarget = normalizeRelease({
    ...target,
    features: [...target.features, ...source.features],
    improvements: [...target.improvements, ...source.improvements],
    fixes: [...target.fixes, ...source.fixes],
    breakingChanges: [...target.breakingChanges, ...source.breakingChanges],
    details: [...target.details, ...source.details],
    detectedAreas: [...new Set([...target.detectedAreas, ...source.detectedAreas])],
    updatedAt: nowIso(),
  });

  const mergedSource = normalizeRelease({
    ...source,
    status: "internal",
    mergedIntoId: target.id,
    updatedAt: nowIso(),
  });

  releases[targetIndex] = mergedTarget;
  releases[sourceIndex] = mergedSource;
  writeJson(RELEASES_KEY, releases);
  return mergedTarget;
}

export function generateReleaseNoteLine(
  verb: ReleaseNoteVerb,
  text: string,
): string {
  return `${RELEASE_NOTE_VERB_LABELS[verb]}: ${text.trim()}`;
}

export function autoGenerateReleaseDetails(
  title: string,
  description: string,
  type: Release["type"],
): string[] {
  const verbMap: Record<Release["type"], ReleaseNoteVerb> = {
    feature: "added",
    ui: "improved",
    fix: "fixed",
    security: "fixed",
    performance: "improved",
    internal: "improved",
  };
  const verb = verbMap[type];
  return [
    generateReleaseNoteLine(verb, title),
    generateReleaseNoteLine("improved", description),
  ];
}

export function getReleasesByStatus(status: ReleaseStatus): Release[] {
  return getAllReleases().filter((release) => release.status === status);
}

/** Merge server-side drafts into localStorage (admin sync). */
export async function syncReleasesFromServer(): Promise<Release[]> {
  if (!isBrowser()) {
    return [];
  }

  try {
    const response = await fetch("/api/admin/releases");
    if (!response.ok) {
      return getAllReleases();
    }

    const payload = (await response.json()) as { releases?: Release[] };
    const serverReleases = (payload.releases ?? []).map(normalizeRelease);
    if (serverReleases.length === 0) {
      return getAllReleases();
    }

    const local = getAllReleases();
    const byId = new Map(local.map((release) => [release.id, release]));

    for (const serverRelease of serverReleases) {
      const existing = byId.get(serverRelease.id);
      if (!existing) {
        byId.set(serverRelease.id, serverRelease);
        continue;
      }
      if (
        new Date(serverRelease.updatedAt).getTime() >
        new Date(existing.updatedAt).getTime()
      ) {
        byId.set(serverRelease.id, serverRelease);
      }
    }

    const merged = sortReleases([...byId.values()]);
    writeJson(RELEASES_KEY, merged);
    return merged;
  } catch {
    return getAllReleases();
  }
}

export async function requestAutoDraft(baseRef?: string): Promise<Release | null> {
  if (!isBrowser()) {
    return null;
  }

  try {
    const response = await fetch("/api/admin/releases/auto-draft", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ baseRef }),
    });
    if (!response.ok) {
      return null;
    }
    const payload = (await response.json()) as { release?: Release | null };
    if (payload.release) {
      await syncReleasesFromServer();
      return normalizeRelease(payload.release);
    }
    return null;
  } catch {
    return null;
  }
}

export function releaseSectionsToForm(release: Release): {
  features: string;
  improvements: string;
  fixes: string;
  breakingChanges: string;
} {
  return {
    features: release.features.join("\n"),
    improvements: release.improvements.join("\n"),
    fixes: release.fixes.join("\n"),
    breakingChanges: release.breakingChanges.join("\n"),
  };
}

export function formSectionsToArrays(form: {
  features: string;
  improvements: string;
  fixes: string;
  breakingChanges: string;
}): Pick<Release, "features" | "improvements" | "fixes" | "breakingChanges" | "details"> {
  const features = form.features
    .split("\n")
    .map((line) => line.trim())
    .filter(Boolean);
  const improvements = form.improvements
    .split("\n")
    .map((line) => line.trim())
    .filter(Boolean);
  const fixes = form.fixes
    .split("\n")
    .map((line) => line.trim())
    .filter(Boolean);
  const breakingChanges = form.breakingChanges
    .split("\n")
    .map((line) => line.trim())
    .filter(Boolean);

  return {
    features,
    improvements,
    fixes,
    breakingChanges,
    details: combineReleaseDetails({
      features,
      improvements,
      fixes,
      breakingChanges,
      details: [],
    }),
  };
}
