/**
 * Release note types — localStorage + `.data/releases.json` today,
 * Supabase `platform_releases` later (see `supabase.ts`).
 */
export type ReleaseCategory =
  | "feature"
  | "fix"
  | "performance"
  | "security"
  | "ui"
  | "internal";

export type ReleaseStatus = "draft" | "published" | "internal";

export type ReleaseNoteVerb = "added" | "improved" | "fixed" | "removed";

/** Product areas detected from git diff or heuristics. */
export type ChangeArea =
  | "homepage"
  | "onboarding"
  | "login"
  | "dashboard"
  | "booking"
  | "admin"
  | "payments"
  | "communications"
  | "updates"
  | "api"
  | "other";

/** Drives semantic version bump rules for 0.x releases. */
export type ReleaseChangeType = "major" | "feature" | "fix" | "ui_tweak";

export type Release = {
  id: string;
  title: string;
  description: string;
  type: ReleaseCategory;
  version: string;
  releaseDate: string;
  summary: string;
  /** Combined bullet list (legacy + display fallback). */
  details: string[];
  features: string[];
  improvements: string[];
  fixes: string[];
  breakingChanges: string[];
  status: ReleaseStatus;
  /** @deprecated Migrated to `status: "internal"` — kept for localStorage back-compat. */
  internalOnly?: boolean;
  autoGenerated: boolean;
  detectedAreas: ChangeArea[];
  mergedIntoId: string | null;
  scheduledAt: string | null;
  publishedAt: string | null;
  createdAt: string;
  updatedAt: string;
};

export type ReleaseSettings = {
  autoGenerateReleaseNotes: boolean;
  autoDraftOnDeploy: boolean;
};

export type CreateReleaseInput = {
  title: string;
  description: string;
  type: ReleaseCategory;
  version: string;
  releaseDate: string;
  summary: string;
  details?: string[];
  features?: string[];
  improvements?: string[];
  fixes?: string[];
  breakingChanges?: string[];
  status?: ReleaseStatus;
  autoGenerated?: boolean;
  detectedAreas?: ChangeArea[];
  scheduledAt?: string | null;
};

/** Patch payload for admin release updates — use `status: "internal"`, not `internalOnly`. */
export type UpdateReleaseInput = Partial<CreateReleaseInput> & {
  status?: ReleaseStatus;
  publishedAt?: string | null;
  mergedIntoId?: string | null;
};

export type ReleaseDraftSuggestion = {
  version: string;
  changeType: ReleaseChangeType;
  title: string;
  summary: string;
  description: string;
  type: ReleaseCategory;
  features: string[];
  improvements: string[];
  fixes: string[];
  breakingChanges: string[];
  detectedAreas: ChangeArea[];
  changedFiles: string[];
};

export const RELEASE_CATEGORY_LABELS: Record<ReleaseCategory, string> = {
  feature: "Feature",
  fix: "Fix",
  performance: "Performance",
  security: "Security",
  ui: "UI",
  internal: "Internal",
};

export const RELEASE_STATUS_LABELS: Record<ReleaseStatus, string> = {
  draft: "Draft",
  published: "Published",
  internal: "Internal",
};

export const RELEASE_NOTE_VERB_LABELS: Record<ReleaseNoteVerb, string> = {
  added: "Added",
  improved: "Improved",
  fixed: "Fixed",
  removed: "Removed",
};

export const CHANGE_AREA_LABELS: Record<ChangeArea, string> = {
  homepage: "Homepage",
  onboarding: "Onboarding",
  login: "Login & auth",
  dashboard: "Dashboard",
  booking: "Booking & sessions",
  admin: "Admin portal",
  payments: "Payments",
  communications: "Communications",
  updates: "Updates & transparency",
  api: "API & integrations",
  other: "Other",
};

export const VERSION_STRATEGY = [
  { version: "0.5", label: "Foundation — core booking, onboarding, transparency" },
  { version: "0.6", label: "Registers & attendance improvements" },
  { version: "0.7", label: "Communications & templates" },
  { version: "0.8", label: "Growth tools & website widget" },
  { version: "0.9", label: "Partnerships & marketplace polish" },
  { version: "1.0", label: "General availability" },
  { version: "1.1", label: "Performance & scale" },
  { version: "1.2", label: "Enterprise & integrations" },
] as const;

export const CURRENT_VERSION = "0.5";
