import type { Review, ReviewResponse } from "./types";

export const DEFAULT_CLUB_REVIEW_SETTINGS = {
  encourageReviews: true,
  incentiveType: "thank_you_email" as const,
  autoRequestEnabled: true,
  requestDelay: "next_day" as const,
  reminderDays: 7 as const,
};

export const MOCK_REVIEWS: Review[] = [
  {
    id: "rev-1",
    rating: 5,
    comment:
      "Loved every minute. Coaches were patient, organised, and made everyone feel welcome from day one.",
    recommend: true,
    title: "Fantastic experience",
    reviewerFirstName: "Sarah",
    childName: "James",
    sessionTitle: "Multi Sports Camp",
    venueName: "Week 2",
    dateAttended: "2026-05-12",
    reviewSubmittedAt: "2026-06-12T10:00:00.000Z",
    bookingId: "booking-demo-1",
    verified: true,
    helpfulCount: 12,
    createdAt: "2026-06-12T10:00:00.000Z",
    status: "published",
    providerId: "local-provider",
    activityId: "demo-activity-1",
    parentId: "parent-demo-1",
    childId: "child-demo-1",
    providerName: "SoccerHQ Dartford",
    aiModerationStatus: "approved",
  },
  {
    id: "rev-2",
    rating: 4,
    comment:
      "Well organised camp with good communication. Drop-off was smooth and everyone came home happy each day.",
    recommend: true,
    title: "Great session overall",
    reviewerFirstName: "Emma",
    childName: "Lily",
    sessionTitle: "Holiday Football Camp",
    venueName: "Green Street",
    dateAttended: "2026-04-28",
    reviewSubmittedAt: "2026-05-24T14:30:00.000Z",
    bookingId: "booking-demo-2",
    verified: true,
    helpfulCount: 8,
    createdAt: "2026-05-24T14:30:00.000Z",
    status: "published",
    providerId: "local-provider",
    activityId: "demo-activity-2",
    parentId: "parent-demo-2",
    providerName: "SoccerHQ Dartford",
    aiModerationStatus: "approved",
  },
  {
    id: "rev-3",
    rating: 3,
    comment:
      "Enjoyable session but felt a bit crowded. Would still recommend for confident kids.",
    recommend: true,
    title: "Enjoyable but room to improve",
    reviewerFirstName: "Verified Parent",
    anonymous: true,
    sessionTitle: "Saturday Football Skills",
    venueName: "Carlsgrove School",
    dateAttended: "2026-03-15",
    reviewSubmittedAt: "2026-02-14T09:00:00.000Z",
    bookingId: "booking-demo-3",
    verified: true,
    helpfulCount: 3,
    createdAt: "2026-02-14T09:00:00.000Z",
    status: "published",
    providerId: "local-provider",
    activityId: "demo-activity-1",
    parentId: "parent-demo-3",
    providerName: "SoccerHQ Dartford",
    aiModerationStatus: "approved",
  },
  {
    id: "rev-4",
    rating: 1,
    comment:
      "Session started late and equipment was limited. Hoping this was a one-off.",
    recommend: false,
    title: "Needs improvement",
    reviewerFirstName: "David",
    childName: "Noah",
    sessionTitle: "Easter Multi Sports",
    venueName: "Foster's Primary",
    dateAttended: "2026-02-20",
    reviewSubmittedAt: "2025-06-14T16:00:00.000Z",
    bookingId: "booking-demo-4",
    verified: true,
    helpfulCount: 1,
    createdAt: "2025-06-14T16:00:00.000Z",
    status: "reported",
    providerId: "local-provider",
    activityId: "demo-activity-3",
    parentId: "parent-demo-4",
    providerName: "SoccerHQ Dartford",
    suspiciousFlag: true,
    aiModerationStatus: "flagged",
  },
  {
    id: "rev-5",
    rating: 5,
    comment:
      "Friendly coaches, great organisation, and we can't wait for next term.",
    recommend: true,
    title: "Fantastic experience",
    reviewerFirstName: "Priya",
    childName: "Anaya",
    sessionTitle: "Girls Football Academy",
    venueName: "Green Street",
    dateAttended: "2026-06-01",
    reviewSubmittedAt: "2026-06-14T08:00:00.000Z",
    bookingId: "booking-demo-5",
    verified: true,
    helpfulCount: 6,
    createdAt: "2026-06-14T08:00:00.000Z",
    status: "pending",
    providerId: "local-provider",
    activityId: "demo-activity-2",
    parentId: "parent-demo-5",
    childId: "child-demo-5",
    providerName: "SoccerHQ Dartford",
    aiModerationStatus: "not_checked",
  },
];

export const MOCK_REVIEW_RESPONSES: ReviewResponse[] = [
  {
    id: "resp-1",
    reviewId: "rev-4",
    providerId: "local-provider",
    body: "Thank you for your feedback. We've since added extra equipment and tightened our start-time process.",
    respondedBy: "SoccerHQ Dartford",
    createdAt: "2026-02-21T10:00:00.000Z",
  },
];
