/** @deprecated Import from `@/constants/footer` instead. Re-exports for backward compatibility. */
export {
  FOOTER_BOTTOM_LINKS,
  FOOTER_COMPANY_LINKS,
  FOOTER_COPYRIGHT_YEAR,
  FOOTER_LINK_COLUMNS,
  FOOTER_NAVY,
  FOOTER_PARENTS_LINKS,
  FOOTER_PLATFORM_LINKS,
  FOOTER_PROVIDERS_LINKS,
  FOOTER_SOCIAL_LINKS,
  FOOTER_SUPPORT_LINKS,
  FOOTER_TEAL,
  FOOTER_TRUST_BADGES,
  FOOTER_TRUST_LINKS,
  type FooterBottomLink,
  type FooterColumnConfig,
  type FooterLinkItem,
  type FooterTrustBadge,
} from "@/constants/footer";
