import type {
  OrgActivity,
  OrgBooking,
  OrgBroadcast,
  OrgCampaign,
  OrgCustomer,
  OrgMessageTemplate,
  OrgParentReply,
  OrgRegisterSession,
  OrgReview,
  OrgStaffMember,
} from "./network-types";

export const DEFAULT_ORG_ACTIVITIES: OrgActivity[] = [
  {
    id: "org_act_001",
    title: "Summer Football Camp",
    type: "camp",
    franchiseeClubId: "franchisee_club_001",
    franchiseeClubName: "PlayVera Juniors — Central",
    venue: "Hyde Park Sports Ground",
    imageUrl:
      "https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=400&h=300&fit=crop",
    startDate: "2026-07-07",
    endDate: "2026-08-15",
    timeLabel: "Mon–Fri · 09:00–12:00",
    booked: 42,
    capacity: 48,
    revenuePence: 756000,
    status: "published",
    canEdit: false,
  },
  {
    id: "org_act_002",
    title: "Junior Tennis Skills",
    type: "course",
    franchiseeClubId: "franchisee_club_001",
    franchiseeClubName: "PlayVera Juniors — Central",
    venue: "Westminster Tennis Centre",
    imageUrl:
      "https://images.unsplash.com/photo-1622279457486-62dcc4a431d6?w=400&h=300&fit=crop",
    startDate: "2026-06-16",
    endDate: "2026-07-21",
    timeLabel: "Mon · 16:00–17:00",
    booked: 18,
    capacity: 20,
    revenuePence: 324000,
    status: "published",
    canEdit: true,
  },
  {
    id: "org_act_003",
    title: "Holiday Multi-Sports",
    type: "camp",
    franchiseeClubId: "franchisee_club_002",
    franchiseeClubName: "PlayVera Juniors — North",
    venue: "Manchester Academy Sports Hall",
    imageUrl:
      "https://images.unsplash.com/photo-1461896836934-ff606ba3681?w=400&h=300&fit=crop",
    startDate: "2026-08-04",
    endDate: "2026-08-22",
    timeLabel: "Tue–Thu · 10:00–15:00",
    booked: 31,
    capacity: 40,
    revenuePence: 558000,
    status: "published",
    canEdit: true,
  },
  {
    id: "org_act_004",
    title: "Saturday Football Club",
    type: "class",
    franchiseeClubId: "franchisee_club_002",
    franchiseeClubName: "PlayVera Juniors — North",
    venue: "Heaton Park Pitches",
    startDate: "2026-06-14",
    endDate: "2026-12-20",
    timeLabel: "Sat · 09:30–11:00",
    booked: 24,
    capacity: 30,
    revenuePence: 432000,
    status: "published",
    canEdit: true,
  },
  {
    id: "org_act_005",
    title: "Birthday Party Package",
    type: "party",
    franchiseeClubId: "franchisee_club_001",
    franchiseeClubName: "PlayVera Juniors — Central",
    venue: "Club HQ — Party Room",
    startDate: "2026-06-01",
    endDate: "2026-12-31",
    timeLabel: "By appointment",
    booked: 8,
    capacity: 12,
    revenuePence: 96000,
    status: "published",
    canEdit: false,
  },
  {
    id: "org_act_006",
    title: "Easter Open Day",
    type: "event",
    franchiseeClubId: "franchisee_club_003",
    franchiseeClubName: "PlayVera Juniors — East",
    venue: "Norwich Community Centre",
    startDate: "2026-04-12",
    endDate: "2026-04-12",
    timeLabel: "Sun · 11:00–15:00",
    booked: 0,
    capacity: 60,
    revenuePence: 0,
    status: "draft",
    canEdit: true,
  },
  {
    id: "org_act_007",
    title: "After-School Gymnastics",
    type: "class",
    franchiseeClubId: "franchisee_club_001",
    franchiseeClubName: "PlayVera Juniors — Central",
    venue: "Chelsea Sports Centre",
    startDate: "2026-09-08",
    endDate: "2026-12-15",
    timeLabel: "Wed · 15:45–16:45",
    booked: 12,
    capacity: 16,
    revenuePence: 216000,
    status: "published",
    canEdit: true,
  },
  {
    id: "org_act_008",
    title: "Winter Basketball League",
    type: "course",
    franchiseeClubId: "franchisee_club_002",
    franchiseeClubName: "PlayVera Juniors — North",
    venue: "Manchester Academy Sports Hall",
    startDate: "2025-11-01",
    endDate: "2026-02-28",
    timeLabel: "Fri · 17:00–18:30",
    booked: 20,
    capacity: 20,
    revenuePence: 360000,
    status: "archived",
    canEdit: false,
  },
];

export const DEFAULT_ORG_BOOKINGS: OrgBooking[] = [
  {
    id: "org_bk_001",
    reference: "PV-2026-0101",
    parentName: "Helen Carter",
    childName: "Mia Carter",
    franchiseeClubId: "franchisee_club_001",
    franchiseeClubName: "PlayVera Juniors — Central",
    activityTitle: "Summer Football Camp",
    sessionDate: "2026-07-14T09:00:00.000Z",
    paymentStatus: "paid",
    bookingStatus: "confirmed",
    amountPence: 18000,
    parentEmail: "helen.carter@example.com",
  },
  {
    id: "org_bk_002",
    reference: "PV-2026-0102",
    parentName: "James Okonkwo",
    childName: "Noah Okonkwo",
    franchiseeClubId: "franchisee_club_001",
    franchiseeClubName: "PlayVera Juniors — Central",
    activityTitle: "Junior Tennis Skills",
    sessionDate: "2026-06-16T16:00:00.000Z",
    paymentStatus: "paid",
    bookingStatus: "confirmed",
    amountPence: 1800,
    parentEmail: "james.okonkwo@example.com",
  },
  {
    id: "org_bk_003",
    reference: "PV-2026-0103",
    parentName: "Sarah Mitchell",
    childName: "Ella Mitchell",
    franchiseeClubId: "franchisee_club_002",
    franchiseeClubName: "PlayVera Juniors — North",
    activityTitle: "Holiday Multi-Sports",
    sessionDate: "2026-08-05T10:00:00.000Z",
    paymentStatus: "paid",
    bookingStatus: "confirmed",
    amountPence: 4500,
    parentEmail: "sarah.mitchell@example.com",
  },
  {
    id: "org_bk_004",
    reference: "PV-2026-0104",
    parentName: "David Hughes",
    childName: "Amelia Hughes",
    franchiseeClubId: "franchisee_club_002",
    franchiseeClubName: "PlayVera Juniors — North",
    activityTitle: "Saturday Football Club",
    sessionDate: "2026-06-14T09:30:00.000Z",
    paymentStatus: "pending",
    bookingStatus: "pending",
    amountPence: 1800,
    parentEmail: "david.hughes@example.com",
  },
  {
    id: "org_bk_005",
    reference: "PV-2026-0105",
    parentName: "Priya Sharma",
    childName: "Arjun Sharma",
    franchiseeClubId: "franchisee_club_001",
    franchiseeClubName: "PlayVera Juniors — Central",
    activityTitle: "After-School Gymnastics",
    sessionDate: "2026-09-10T15:45:00.000Z",
    paymentStatus: "paid",
    bookingStatus: "confirmed",
    amountPence: 1800,
    parentEmail: "priya.sharma@example.com",
  },
  {
    id: "org_bk_006",
    reference: "PV-2026-0106",
    parentName: "Tom Bradley",
    childName: "Lucy Bradley",
    franchiseeClubId: "franchisee_club_001",
    franchiseeClubName: "PlayVera Juniors — Central",
    activityTitle: "Birthday Party Package",
    sessionDate: "2026-06-28T14:00:00.000Z",
    paymentStatus: "refunded",
    bookingStatus: "cancelled",
    amountPence: 12000,
    parentEmail: "tom.bradley@example.com",
  },
  {
    id: "org_bk_007",
    reference: "PV-2026-0107",
    parentName: "Emma Walsh",
    childName: "Jack Walsh",
    franchiseeClubId: "franchisee_club_002",
    franchiseeClubName: "PlayVera Juniors — North",
    activityTitle: "Holiday Multi-Sports",
    sessionDate: "2026-08-07T10:00:00.000Z",
    paymentStatus: "partial_refund",
    bookingStatus: "refund_requested",
    amountPence: 4500,
    parentEmail: "emma.walsh@example.com",
  },
  {
    id: "org_bk_008",
    reference: "PV-2026-0108",
    parentName: "Helen Carter",
    childName: "Mia Carter",
    franchiseeClubId: "franchisee_club_002",
    franchiseeClubName: "PlayVera Juniors — North",
    activityTitle: "Saturday Football Club",
    sessionDate: "2026-06-21T09:30:00.000Z",
    paymentStatus: "paid",
    bookingStatus: "confirmed",
    amountPence: 1800,
    parentEmail: "helen.carter@example.com",
  },
  {
    id: "org_bk_009",
    reference: "PV-2026-0109",
    parentName: "Chris Nguyen",
    childName: "Lily Nguyen",
    franchiseeClubId: "franchisee_club_001",
    franchiseeClubName: "PlayVera Juniors — Central",
    activityTitle: "Junior Tennis Skills",
    sessionDate: "2026-06-23T16:00:00.000Z",
    paymentStatus: "failed",
    bookingStatus: "cancelled",
    amountPence: 1800,
    parentEmail: "chris.nguyen@example.com",
  },
  {
    id: "org_bk_010",
    reference: "PV-2026-0110",
    parentName: "Sarah Mitchell",
    childName: "Leo Mitchell",
    franchiseeClubId: "franchisee_club_001",
    franchiseeClubName: "PlayVera Juniors — Central",
    activityTitle: "Summer Football Camp",
    sessionDate: "2026-07-21T09:00:00.000Z",
    paymentStatus: "paid",
    bookingStatus: "confirmed",
    amountPence: 18000,
    parentEmail: "sarah.mitchell@example.com",
  },
];

export const DEFAULT_ORG_REGISTERS: OrgRegisterSession[] = [
  {
    id: "org_reg_001",
    sessionTitle: "Junior Tennis Skills — 16 Jun",
    franchiseeClubId: "franchisee_club_001",
    franchiseeClubName: "PlayVera Juniors — Central",
    venue: "Westminster Tennis Centre",
    activityTitle: "Junior Tennis Skills",
    date: "2026-06-16",
    timeLabel: "16:00–17:00",
    booked: 18,
    present: 16,
    absent: 2,
    medicalFlags: 1,
    status: "closed",
  },
  {
    id: "org_reg_002",
    sessionTitle: "Saturday Football Club — 14 Jun",
    franchiseeClubId: "franchisee_club_002",
    franchiseeClubName: "PlayVera Juniors — North",
    venue: "Heaton Park Pitches",
    activityTitle: "Saturday Football Club",
    date: "2026-06-14",
    timeLabel: "09:30–11:00",
    booked: 24,
    present: 22,
    absent: 2,
    medicalFlags: 0,
    status: "closed",
  },
  {
    id: "org_reg_003",
    sessionTitle: "Summer Football Camp — Week 1",
    franchiseeClubId: "franchisee_club_001",
    franchiseeClubName: "PlayVera Juniors — Central",
    venue: "Hyde Park Sports Ground",
    activityTitle: "Summer Football Camp",
    date: "2026-07-07",
    timeLabel: "09:00–12:00",
    booked: 42,
    present: 0,
    absent: 0,
    medicalFlags: 3,
    status: "open",
  },
  {
    id: "org_reg_004",
    sessionTitle: "Holiday Multi-Sports — 5 Aug",
    franchiseeClubId: "franchisee_club_002",
    franchiseeClubName: "PlayVera Juniors — North",
    venue: "Manchester Academy Sports Hall",
    activityTitle: "Holiday Multi-Sports",
    date: "2026-08-05",
    timeLabel: "10:00–15:00",
    booked: 31,
    present: 0,
    absent: 0,
    medicalFlags: 2,
    status: "open",
  },
  {
    id: "org_reg_005",
    sessionTitle: "After-School Gymnastics — 10 Sep",
    franchiseeClubId: "franchisee_club_001",
    franchiseeClubName: "PlayVera Juniors — Central",
    venue: "Chelsea Sports Centre",
    activityTitle: "After-School Gymnastics",
    date: "2026-09-10",
    timeLabel: "15:45–16:45",
    booked: 12,
    present: 0,
    absent: 0,
    medicalFlags: 1,
    status: "open",
  },
  {
    id: "org_reg_006",
    sessionTitle: "Junior Tennis Skills — 23 Jun",
    franchiseeClubId: "franchisee_club_001",
    franchiseeClubName: "PlayVera Juniors — Central",
    venue: "Westminster Tennis Centre",
    activityTitle: "Junior Tennis Skills",
    date: "2026-06-23",
    timeLabel: "16:00–17:00",
    booked: 17,
    present: 0,
    absent: 0,
    medicalFlags: 1,
    status: "in_progress",
  },
];

export const DEFAULT_ORG_CUSTOMERS: OrgCustomer[] = [
  {
    id: "cust_helen_carter",
    parentName: "Helen Carter",
    children: ["Mia Carter"],
    email: "helen.carter@example.com",
    phone: "07700 900 101",
    franchiseeClubs: [
      "PlayVera Juniors — Central",
      "PlayVera Juniors — North",
    ],
    totalBookings: 4,
    totalSpendPence: 39600,
    lastBookingDate: "2026-06-21T09:30:00.000Z",
    isActive: true,
    isRepeat: true,
  },
  {
    id: "cust_james_okonkwo",
    parentName: "James Okonkwo",
    children: ["Noah Okonkwo"],
    email: "james.okonkwo@example.com",
    phone: "07700 900 202",
    franchiseeClubs: ["PlayVera Juniors — Central"],
    totalBookings: 2,
    totalSpendPence: 3600,
    lastBookingDate: "2026-06-16T16:00:00.000Z",
    isActive: true,
    isRepeat: true,
  },
  {
    id: "cust_sarah_mitchell",
    parentName: "Sarah Mitchell",
    children: ["Ella Mitchell", "Leo Mitchell"],
    email: "sarah.mitchell@example.com",
    phone: "07700 900 303",
    franchiseeClubs: [
      "PlayVera Juniors — Central",
      "PlayVera Juniors — North",
    ],
    totalBookings: 5,
    totalSpendPence: 42300,
    lastBookingDate: "2026-07-21T09:00:00.000Z",
    isActive: true,
    isRepeat: true,
  },
  {
    id: "cust_david_hughes",
    parentName: "David Hughes",
    children: ["Amelia Hughes"],
    email: "david.hughes@example.com",
    phone: "07700 900 404",
    franchiseeClubs: ["PlayVera Juniors — North"],
    totalBookings: 1,
    totalSpendPence: 1800,
    lastBookingDate: "2026-06-14T09:30:00.000Z",
    isActive: true,
    isRepeat: false,
  },
  {
    id: "cust_priya_sharma",
    parentName: "Priya Sharma",
    children: ["Arjun Sharma"],
    email: "priya.sharma@example.com",
    phone: "07700 900 505",
    franchiseeClubs: ["PlayVera Juniors — Central"],
    totalBookings: 3,
    totalSpendPence: 5400,
    lastBookingDate: "2026-09-10T15:45:00.000Z",
    isActive: true,
    isRepeat: true,
  },
  {
    id: "cust_tom_bradley",
    parentName: "Tom Bradley",
    children: ["Lucy Bradley"],
    email: "tom.bradley@example.com",
    phone: "07700 900 606",
    franchiseeClubs: ["PlayVera Juniors — Central"],
    totalBookings: 1,
    totalSpendPence: 0,
    lastBookingDate: "2026-06-28T14:00:00.000Z",
    isActive: false,
    isRepeat: false,
  },
  {
    id: "cust_emma_walsh",
    parentName: "Emma Walsh",
    children: ["Jack Walsh"],
    email: "emma.walsh@example.com",
    phone: "07700 900 707",
    franchiseeClubs: ["PlayVera Juniors — North"],
    totalBookings: 2,
    totalSpendPence: 6750,
    lastBookingDate: "2026-08-07T10:00:00.000Z",
    isActive: true,
    isRepeat: true,
  },
];

export const DEFAULT_ORG_TEMPLATES: OrgMessageTemplate[] = [
  {
    id: "tpl_001",
    name: "Booking confirmation",
    channel: "email",
    trigger: "On booking confirmed",
    lastEdited: "2026-05-10T10:00:00.000Z",
    enabled: true,
  },
  {
    id: "tpl_002",
    name: "Session reminder (24h)",
    channel: "email",
    trigger: "24 hours before session",
    lastEdited: "2026-05-12T14:00:00.000Z",
    enabled: true,
  },
  {
    id: "tpl_003",
    name: "Review request",
    channel: "email",
    trigger: "After session attended",
    lastEdited: "2026-04-20T09:00:00.000Z",
    enabled: true,
  },
  {
    id: "tpl_004",
    name: "Refund processed",
    channel: "email",
    trigger: "On refund completed",
    lastEdited: "2026-03-01T11:00:00.000Z",
    enabled: true,
  },
  {
    id: "tpl_005",
    name: "Network newsletter",
    channel: "email",
    trigger: "Manual broadcast",
    lastEdited: "2026-06-01T08:00:00.000Z",
    enabled: false,
  },
];

export const DEFAULT_ORG_PARENT_REPLIES: OrgParentReply[] = [
  {
    id: "reply_001",
    parentName: "Helen Carter",
    franchiseeClubName: "PlayVera Juniors — Central",
    activityTitle: "Summer Football Camp",
    subject: "Can Mia join week 2 only?",
    preview: "Hi, we'd like to switch to week 2 of camp if there's space...",
    receivedAt: "2026-06-13T10:22:00.000Z",
    status: "open",
    parentType: "returning",
    bookingStatus: "confirmed",
  },
  {
    id: "reply_002",
    parentName: "David Hughes",
    franchiseeClubName: "PlayVera Juniors — North",
    activityTitle: "Saturday Football Club",
    subject: "Payment not going through",
    preview: "I've tried twice and my card keeps failing at checkout...",
    receivedAt: "2026-06-12T16:45:00.000Z",
    status: "pending",
    parentType: "new",
    bookingStatus: "pending",
  },
  {
    id: "reply_003",
    parentName: "Emma Walsh",
    franchiseeClubName: "PlayVera Juniors — North",
    activityTitle: "Holiday Multi-Sports",
    subject: "Refund request — missed session",
    preview: "Jack was unwell and couldn't attend Tuesday's session...",
    receivedAt: "2026-06-11T09:10:00.000Z",
    status: "open",
    parentType: "returning",
    bookingStatus: "refund_requested",
  },
  {
    id: "reply_004",
    parentName: "Chris Nguyen",
    franchiseeClubName: "PlayVera Juniors — Central",
    activityTitle: "Junior Tennis Skills",
    subject: "Re: booking cancelled",
    preview: "Thanks for letting me know — I'll try booking again...",
    receivedAt: "2026-06-10T14:00:00.000Z",
    status: "resolved",
    parentType: "new",
    bookingStatus: "cancelled",
  },
];

export const DEFAULT_ORG_CAMPAIGNS: OrgCampaign[] = [
  {
    id: "camp_001",
    name: "Summer camp early bird",
    franchiseeClubName: "All clubs",
    audience: "Parents with past camp bookings",
    sentAt: "2026-05-15T09:00:00.000Z",
    openRate: 42,
    status: "sent",
  },
  {
    id: "camp_002",
    name: "North club open day",
    franchiseeClubName: "PlayVera Juniors — North",
    audience: "Local postcode radius",
    sentAt: "2026-06-01T10:00:00.000Z",
    openRate: 38,
    status: "sent",
  },
  {
    id: "camp_003",
    name: "September term reminder",
    franchiseeClubName: "PlayVera Juniors — Central",
    audience: "Active customers",
    sentAt: "2026-08-25T08:00:00.000Z",
    openRate: 0,
    status: "scheduled",
  },
];

export const DEFAULT_ORG_BROADCASTS: OrgBroadcast[] = [
  {
    id: "bc_001",
    title: "Safeguarding policy update",
    scope: "All franchisee clubs",
    sentAt: "2026-05-20T11:00:00.000Z",
    recipientCount: 412,
    status: "sent",
  },
  {
    id: "bc_002",
    title: "New booking platform features",
    scope: "Club managers only",
    sentAt: "2026-06-05T09:30:00.000Z",
    recipientCount: 6,
    status: "sent",
  },
  {
    id: "bc_003",
    title: "Summer network newsletter",
    scope: "All parents (opt-in)",
    sentAt: "2026-06-20T08:00:00.000Z",
    recipientCount: 0,
    status: "draft",
  },
];

export const DEFAULT_ORG_REVIEWS: OrgReview[] = [
  {
    id: "org_rev_001",
    rating: 5,
    body: "Brilliant coaches and Mia loved every session. Great communication from the club too.",
    sessionTitle: "Summer Football Camp",
    franchiseeClubId: "franchisee_club_001",
    franchiseeClubName: "PlayVera Juniors — Central",
    reviewedAt: "2026-06-10T18:00:00.000Z",
    status: "published",
    parentName: "Helen C.",
    flagged: false,
  },
  {
    id: "org_rev_002",
    rating: 4,
    body: "Really well organised tennis sessions. Would be 5 stars with more parking nearby.",
    sessionTitle: "Junior Tennis Skills",
    franchiseeClubId: "franchisee_club_001",
    franchiseeClubName: "PlayVera Juniors — Central",
    reviewedAt: "2026-06-08T12:30:00.000Z",
    status: "published",
    parentName: "James O.",
    flagged: false,
  },
  {
    id: "org_rev_003",
    rating: 5,
    body: "North club team are fantastic. Ella and Leo both enjoy Saturday football.",
    sessionTitle: "Saturday Football Club",
    franchiseeClubId: "franchisee_club_002",
    franchiseeClubName: "PlayVera Juniors — North",
    reviewedAt: "2026-06-12T20:15:00.000Z",
    status: "published",
    parentName: "Sarah M.",
    flagged: false,
  },
  {
    id: "org_rev_004",
    rating: 2,
    body: "Session was overcrowded and we didn't get the refund promised.",
    sessionTitle: "Holiday Multi-Sports",
    franchiseeClubId: "franchisee_club_002",
    franchiseeClubName: "PlayVera Juniors — North",
    reviewedAt: "2026-06-11T09:00:00.000Z",
    status: "reported",
    parentName: "Emma W.",
    flagged: true,
  },
  {
    id: "org_rev_005",
    rating: 5,
    body: "Gymnastics coach is patient and encouraging. Arjun's confidence has grown loads.",
    sessionTitle: "After-School Gymnastics",
    franchiseeClubId: "franchisee_club_001",
    franchiseeClubName: "PlayVera Juniors — Central",
    reviewedAt: "2026-06-01T16:00:00.000Z",
    status: "published",
    parentName: "Priya S.",
    flagged: false,
  },
  {
    id: "org_rev_006",
    rating: 3,
    body: "Party was fine but started 20 minutes late.",
    sessionTitle: "Birthday Party Package",
    franchiseeClubId: "franchisee_club_001",
    franchiseeClubName: "PlayVera Juniors — Central",
    reviewedAt: "2026-05-28T19:00:00.000Z",
    status: "pending",
    parentName: "Tom B.",
    flagged: false,
  },
];

export const DEFAULT_ORG_STAFF: OrgStaffMember[] = [
  {
    id: "staff_ho_001",
    name: "Organisation Owner",
    email: "organisation@test.activeora.co.uk",
    role: "organisation_owner",
    assignedClubs: ["All clubs"],
    status: "active",
    lastActiveAt: "2026-06-14T08:00:00.000Z",
    section: "head_office",
  },
  {
    id: "staff_ho_002",
    name: "Rachel Foster",
    email: "rachel.foster@playvera.example",
    role: "organisation_manager",
    assignedClubs: ["All clubs"],
    status: "active",
    lastActiveAt: "2026-06-13T17:30:00.000Z",
    section: "head_office",
  },
  {
    id: "staff_ho_003",
    name: "Mark Davies",
    email: "mark.davies@playvera.example",
    role: "finance_admin",
    assignedClubs: ["All clubs"],
    status: "active",
    lastActiveAt: "2026-06-12T10:00:00.000Z",
    section: "head_office",
  },
  {
    id: "staff_ho_004",
    name: "Lisa Chen",
    email: "lisa.chen@playvera.example",
    role: "support_admin",
    assignedClubs: ["All clubs"],
    status: "active",
    lastActiveAt: "2026-06-14T07:45:00.000Z",
    section: "head_office",
  },
  {
    id: "staff_fc_001",
    name: "Club Owner",
    email: "club@test.activeora.co.uk",
    role: "club_manager",
    assignedClubs: ["PlayVera Juniors — Central"],
    status: "active",
    lastActiveAt: "2026-06-14T09:00:00.000Z",
    section: "franchisee",
  },
  {
    id: "staff_fc_002",
    name: "Sarah Mitchell",
    email: "north@playvera.example",
    role: "club_manager",
    assignedClubs: ["PlayVera Juniors — North"],
    status: "active",
    lastActiveAt: "2026-06-13T14:20:00.000Z",
    section: "franchisee",
  },
  {
    id: "staff_fc_003",
    name: "Coach Tom",
    email: "tom.coach@playvera.example",
    role: "coach",
    assignedClubs: ["PlayVera Juniors — Central"],
    status: "active",
    lastActiveAt: "2026-06-14T08:30:00.000Z",
    section: "franchisee",
  },
  {
    id: "staff_fc_004",
    name: "Coach Amy",
    email: "amy.coach@playvera.example",
    role: "coach",
    assignedClubs: ["PlayVera Juniors — North"],
    status: "active",
    lastActiveAt: "2026-06-13T16:00:00.000Z",
    section: "franchisee",
  },
  {
    id: "staff_inv_001",
    name: "James Chen",
    email: "east@playvera.example",
    role: "club_manager",
    assignedClubs: ["PlayVera Juniors — East"],
    status: "invited",
    lastActiveAt: "",
    section: "pending",
  },
  {
    id: "staff_inv_002",
    name: "New Finance Analyst",
    email: "finance.new@playvera.example",
    role: "finance_admin",
    assignedClubs: ["All clubs"],
    status: "invited",
    lastActiveAt: "",
    section: "pending",
  },
];
