import type { InboxItem } from "./types";

export const INBOX_STORAGE_KEY = "activora-club-inbox";

export const SEED_INBOX_ITEMS: InboxItem[] = [
  {
    id: "inbox_notif_001",
    type: "notification",
    category: "notifications",
    title: "New dashboard analytics",
    preview:
      "Track session fill rates and revenue trends from your dashboard home.",
    timestamp: "2026-06-13T09:00:00Z",
    status: "unread",
    priority: "normal",
    subtype: "platform_update",
    body: "We've added fill-rate charts and a revenue breakdown to your club dashboard. Visit Dashboard to explore the new panels.",
    href: "/club/dashboard",
  },
  {
    id: "inbox_review_001",
    type: "review",
    category: "reviews",
    title: "New 5-star review from Emma T.",
    preview: "Brilliant coaching session — my daughter loved it!",
    timestamp: "2026-06-13T08:15:00Z",
    status: "unread",
    priority: "normal",
    subtype: "parent_rating",
    reviewId: "rev_001",
    metadata: { rating: 5, parentName: "Emma Thompson" },
    href: "/club/reviews",
    body: "Brilliant coaching session — my daughter loved it! The coaches were friendly and organised. We'll definitely book again.",
  },
  {
    id: "inbox_booking_001",
    type: "booking",
    category: "bookings",
    title: "New booking — Saturday Football Skills",
    preview: "Oliver Reed booked for Sat 21 Jun, 10:00.",
    timestamp: "2026-06-12T18:42:00Z",
    status: "unread",
    priority: "normal",
    subtype: "booking_created",
    bookingId: "bk_001",
    href: "/club/bookings",
    body: "Oliver Reed (age 8) has booked Saturday Football Skills on 21 Jun at 10:00. Parent: Sarah Reed.",
  },
  {
    id: "inbox_booking_002",
    type: "booking",
    category: "bookings",
    title: "Booking cancelled — Mini Tennis",
    preview: "Lucy Chen cancelled her booking for Wed 18 Jun.",
    timestamp: "2026-06-12T14:20:00Z",
    status: "unread",
    priority: "high",
    subtype: "booking_cancelled",
    bookingId: "bk_002",
    href: "/club/bookings",
    body: "Lucy Chen cancelled Mini Tennis on Wed 18 Jun at 16:00. A spot has opened on the register.",
  },
  {
    id: "inbox_booking_003",
    type: "booking",
    category: "bookings",
    title: "Session reminder — Gymnastics Taster",
    preview: "Gymnastics Taster starts in 24 hours. 12 children registered.",
    timestamp: "2026-06-12T07:00:00Z",
    status: "read",
    priority: "normal",
    subtype: "session_reminder",
    bookingId: "bk_003",
    href: "/club/bookings",
    body: "Gymnastics Taster is tomorrow at 09:30. Check your register and confirm staff are assigned.",
  },
  {
    id: "inbox_booking_004",
    type: "booking",
    category: "bookings",
    title: "New booking — Holiday Camp Day 2",
    preview: "Noah Patel booked for Mon 23 Jun, full day.",
    timestamp: "2026-06-11T20:10:00Z",
    status: "unread",
    priority: "normal",
    subtype: "booking_created",
    bookingId: "bk_004",
    href: "/club/bookings",
    body: "Noah Patel booked Holiday Camp Day 2 on Mon 23 Jun. Parent: Priya Patel.",
  },
  {
    id: "inbox_payment_001",
    type: "payment",
    category: "payments",
    title: "Payout completed — £1,240.50",
    preview: "Your weekly payout has been sent to your bank account.",
    timestamp: "2026-06-12T06:30:00Z",
    status: "unread",
    priority: "normal",
    subtype: "payout_completed",
    paymentId: "pay_001",
    href: "/club/finance",
    body: "£1,240.50 has been transferred to your connected bank account. It may take 1–2 business days to appear.",
    metadata: { amount: 1240.5, currency: "GBP" },
  },
  {
    id: "inbox_payment_002",
    type: "payment",
    category: "payments",
    title: "Refund requested — £18.00",
    preview: "Parent requested a refund for Saturday Football Skills.",
    timestamp: "2026-06-11T11:45:00Z",
    status: "read",
    priority: "high",
    subtype: "refund_requested",
    paymentId: "pay_002",
    href: "/club/finance",
    body: "Sarah Reed requested a refund of £18.00 for Oliver's booking. Review and approve from Finance → Refunds.",
    metadata: { amount: 18, currency: "GBP" },
  },
  {
    id: "inbox_system_001",
    type: "system",
    category: "system",
    title: "Complete your club profile",
    preview: "Add photos and social links to improve discoverability.",
    timestamp: "2026-06-10T10:00:00Z",
    status: "unread",
    priority: "normal",
    subtype: "onboarding_reminder",
    href: "/club/settings/profile",
    body: "Clubs with complete profiles get 40% more bookings. Add your logo, cover photo, and social links to finish setup.",
  },
  {
    id: "inbox_system_002",
    type: "system",
    category: "system",
    title: "Stripe verification required",
    preview: "Additional documents needed to continue receiving payouts.",
    timestamp: "2026-06-09T15:30:00Z",
    status: "read",
    priority: "high",
    subtype: "account_alert",
    href: "/club/finance",
    body: "Stripe needs additional identity verification before your next payout. Complete verification in Finance → Stripe Connect.",
  },
  {
    id: "inbox_notif_002",
    type: "notification",
    category: "notifications",
    title: "Summer feature preview",
    preview: "SMS reminders and WhatsApp booking confirmations are coming soon.",
    timestamp: "2026-06-08T12:00:00Z",
    status: "read",
    priority: "normal",
    subtype: "platform_update",
    body: "We're building SMS and WhatsApp channels for parent communications. Opt in from Communications when available.",
    href: "/club/communications",
  },
];
