import type { Partner, PartnerClaim } from "./types";

export const PARTNERS_STORAGE_KEY = "activora-partners";
export const PARTNER_CLAIMS_STORAGE_KEY = "activora-partner-claims";
export const CLUB_SAVED_PARTNERS_KEY = "activora-club-saved-partners";

export const LOGO_DATA_URL_MAX_BYTES = 80_000;

const daysAgo = (days: number): string => {
  const date = new Date();
  date.setDate(date.getDate() - days);
  return date.toISOString();
};

const monthsAhead = (months: number): string => {
  const date = new Date();
  date.setMonth(date.getMonth() + months);
  return date.toISOString().slice(0, 10);
};

export const SEED_PARTNERS: Partner[] = [
  {
    id: "partner_sportequip",
    name: "SportEquip Pro",
    slug: "sportequip-pro",
    category: "equipment",
    shortDescription:
      "Quality balls, cones, bibs and training gear with fast UK delivery for grassroots clubs.",
    benefitOffered: "15% off first equipment order",
    benefitType: "discount",
    website: "https://sportequip.example.com",
    contactEmail: "clubs@sportequip.example.com",
    contactPhone: "0800 123 4567",
    logoDataUrl: null,
    offer: {
      title: "Activora club equipment discount",
      description:
        "Save 15% on your first order of £150 or more. Ideal for new season kit refreshes.",
      terms: "Valid for Activora clubs only. Excludes clearance items.",
      promoCode: "ACTIVORA15",
      validUntil: monthsAhead(6),
    },
    status: "featured",
    recommended: true,
    isNew: false,
    analytics: { views: 428, clicks: 156, claims: 34, introductions: 8 },
    createdAt: daysAgo(120),
    updatedAt: daysAgo(3),
  },
  {
    id: "partner_clubcover",
    name: "ClubCover Insurance",
    slug: "clubcover-insurance",
    category: "insurance",
    shortDescription:
      "Specialist public liability and equipment cover tailored for activity providers and clubs.",
    benefitOffered: "Free policy review + 10% first-year discount",
    benefitType: "exclusive_pricing",
    website: "https://clubcover.example.com",
    contactEmail: "partnerships@clubcover.example.com",
    contactPhone: "020 7946 0123",
    logoDataUrl: null,
    offer: {
      title: "Activora insurance review",
      description:
        "Complimentary cover review with a dedicated broker and preferential rates for Activora clubs.",
      terms: "Subject to underwriting. Minimum premium applies.",
      promoCode: "ACTIVORA-INS",
      validUntil: monthsAhead(12),
    },
    status: "approved",
    recommended: true,
    isNew: false,
    analytics: { views: 312, clicks: 98, claims: 21, introductions: 14 },
    createdAt: daysAgo(200),
    updatedAt: daysAgo(10),
  },
  {
    id: "partner_coachacademy",
    name: "CoachAcademy UK",
    slug: "coachacademy-uk",
    category: "training",
    shortDescription:
      "Online and in-person coaching qualifications, safeguarding and first-aid courses.",
    benefitOffered: "20% off safeguarding refresher courses",
    benefitType: "discount",
    website: "https://coachacademy.example.com",
    contactEmail: "clubs@coachacademy.example.com",
    contactPhone: "",
    logoDataUrl: null,
    offer: {
      title: "Safeguarding refresher bundle",
      description:
        "Discounted safeguarding and first-aid refreshers for your coaching team.",
      terms: "Per coach. Online modules included.",
      promoCode: "SAFE20",
      validUntil: monthsAhead(4),
    },
    status: "approved",
    recommended: false,
    isNew: false,
    analytics: { views: 189, clicks: 67, claims: 15, introductions: 3 },
    createdAt: daysAgo(90),
    updatedAt: daysAgo(20),
  },
  {
    id: "partner_numbersfirst",
    name: "NumbersFirst Accountants",
    slug: "numbersfirst-accountants",
    category: "accounting",
    shortDescription:
      "Chartered accountants specialising in clubs, charities and community interest companies.",
    benefitOffered: "Free initial bookkeeping health check",
    benefitType: "free_trial",
    website: "https://numbersfirst.example.com",
    contactEmail: "hello@numbersfirst.example.com",
    contactPhone: "0161 555 0199",
    logoDataUrl: null,
    offer: {
      title: "Bookkeeping health check",
      description:
        "A 30-minute review of your club accounts with actionable recommendations.",
      terms: "One session per club. No obligation.",
      promoCode: "",
      validUntil: monthsAhead(8),
    },
    status: "approved",
    recommended: false,
    isNew: true,
    analytics: { views: 76, clicks: 28, claims: 6, introductions: 5 },
    createdAt: daysAgo(14),
    updatedAt: daysAgo(2),
  },
  {
    id: "partner_clublaw",
    name: "ClubLaw Partners",
    slug: "clublaw-partners",
    category: "legal",
    shortDescription:
      "Employment, safeguarding and venue hire contracts for sports and activity organisations.",
    benefitOffered: "Fixed-fee contract review from £149",
    benefitType: "exclusive_pricing",
    website: "https://clublaw.example.com",
    contactEmail: "enquiries@clublaw.example.com",
    contactPhone: "",
    logoDataUrl: null,
    offer: {
      title: "Contract review package",
      description:
        "Review of coach contracts, venue hire agreements or volunteer policies.",
      terms: "Up to 10 pages. Additional work quoted separately.",
      promoCode: "CLUBLAW149",
      validUntil: monthsAhead(6),
    },
    status: "approved",
    recommended: false,
    isNew: false,
    analytics: { views: 94, clicks: 31, claims: 4, introductions: 7 },
    createdAt: daysAgo(150),
    updatedAt: daysAgo(45),
  },
  {
    id: "partner_growyourclub",
    name: "GrowYourClub Marketing",
    slug: "growyourclub-marketing",
    category: "marketing",
    shortDescription:
      "Social media, email campaigns and local SEO to fill your sessions faster.",
    benefitOffered: "Free 30-day social content plan",
    benefitType: "free_trial",
    website: "https://growyourclub.example.com",
    contactEmail: "hello@growyourclub.example.com",
    contactPhone: "0117 555 0188",
    logoDataUrl: null,
    offer: {
      title: "Social starter plan",
      description:
        "A month of post ideas, captions and scheduling tips tailored to your club.",
      terms: "Digital delivery within 5 working days.",
      promoCode: "GROW30",
      validUntil: monthsAhead(3),
    },
    status: "featured",
    recommended: true,
    isNew: false,
    analytics: { views: 267, clicks: 112, claims: 28, introductions: 6 },
    createdAt: daysAgo(80),
    updatedAt: daysAgo(7),
  },
  {
    id: "partner_staffperks",
    name: "StaffPerks Hub",
    slug: "staffperks-hub",
    category: "staff_benefits",
    shortDescription:
      "Discounts on gym memberships, wellbeing apps and retail for your coaching team.",
    benefitOffered: "Free staff benefits portal for up to 20 coaches",
    benefitType: "membership",
    website: "https://staffperks.example.com",
    contactEmail: "clubs@staffperks.example.com",
    contactPhone: "",
    logoDataUrl: null,
    offer: {
      title: "Coach wellbeing portal",
      description:
        "Give your team access to hundreds of high-street and wellbeing discounts.",
      terms: "12-month Activora offer. Renew at standard rates.",
      promoCode: "STAFFFREE20",
      validUntil: monthsAhead(12),
    },
    status: "approved",
    recommended: true,
    isNew: false,
    analytics: { views: 143, clicks: 54, claims: 11, introductions: 2 },
    createdAt: daysAgo(60),
    updatedAt: daysAgo(15),
  },
  {
    id: "partner_pitchperfect",
    name: "PitchPerfect Venues",
    slug: "pitchperfect-venues",
    category: "venues",
    shortDescription:
      "Indoor and outdoor hire across the UK with flexible evening and weekend slots.",
    benefitOffered: "Waived booking fee on first venue hire",
    benefitType: "referral",
    website: "https://pitchperfect.example.com",
    contactEmail: "bookings@pitchperfect.example.com",
    contactPhone: "0333 555 0100",
    logoDataUrl: null,
    offer: {
      title: "First booking incentive",
      description:
        "No admin fee on your first venue booking through PitchPerfect.",
      terms: "Selected venues. Peak slots may vary.",
      promoCode: "PITCHFREE",
      validUntil: monthsAhead(5),
    },
    status: "approved",
    recommended: false,
    isNew: false,
    analytics: { views: 201, clicks: 88, claims: 19, introductions: 9 },
    createdAt: daysAgo(110),
    updatedAt: daysAgo(25),
  },
  {
    id: "partner_playmore",
    name: "PlayMore Foundation",
    slug: "playmore-foundation",
    category: "community_programmes",
    shortDescription:
      "Grants and outreach programmes to help underrepresented children access sport.",
    benefitOffered: "Grant application support for eligible clubs",
    benefitType: "service_bundle",
    website: "https://playmore.example.org",
    contactEmail: "grants@playmore.example.org",
    contactPhone: "",
    logoDataUrl: null,
    offer: {
      title: "Participation grant support",
      description:
        "Guidance on applying for small grants to subsidise places for families in need.",
      terms: "Eligibility criteria apply. UK registered clubs.",
      promoCode: "",
      validUntil: monthsAhead(10),
    },
    status: "approved",
    recommended: false,
    isNew: false,
    analytics: { views: 118, clicks: 42, claims: 8, introductions: 12 },
    createdAt: daysAgo(180),
    updatedAt: daysAgo(30),
  },
  {
    id: "partner_sessiontech",
    name: "SessionTech",
    slug: "sessiontech",
    category: "technology",
    shortDescription:
      "Attendance kiosks, QR check-in and parent communication tools that complement Activora.",
    benefitOffered: "3-month free kiosk trial",
    benefitType: "free_trial",
    website: "https://sessiontech.example.com",
    contactEmail: "sales@sessiontech.example.com",
    contactPhone: "020 3555 0177",
    logoDataUrl: null,
    offer: {
      title: "Kiosk trial programme",
      description:
        "Try SessionTech check-in kiosks at your venue with full setup support.",
      terms: "Hardware deposit may apply. One trial per club.",
      promoCode: "KIOSK3",
      validUntil: monthsAhead(6),
    },
    status: "approved",
    recommended: false,
    isNew: true,
    analytics: { views: 52, clicks: 19, claims: 3, introductions: 1 },
    createdAt: daysAgo(10),
    updatedAt: daysAgo(1),
  },
  {
    id: "partner_activpay",
    name: "ActivPay Finance",
    slug: "activpay-finance",
    category: "finance",
    shortDescription:
      "Business accounts, cashflow tools and invoice finance built for activity providers.",
    benefitOffered: "£50 account credit for new business accounts",
    benefitType: "referral",
    website: "https://activpay.example.com",
    contactEmail: "clubs@activpay.example.com",
    contactPhone: "",
    logoDataUrl: null,
    offer: {
      title: "Business account welcome credit",
      description:
        "Open a fee-free business account and receive £50 credit after your first deposit.",
      terms: "FCA-regulated partner. Identity checks required.",
      promoCode: "ACTIVPAY50",
      validUntil: monthsAhead(9),
    },
    status: "pending",
    recommended: false,
    isNew: true,
    analytics: { views: 0, clicks: 0, claims: 0, introductions: 0 },
    createdAt: daysAgo(5),
    updatedAt: daysAgo(5),
  },
  {
    id: "partner_joinin",
    name: "JoinIn Participation",
    slug: "joinin-participation",
    category: "participation",
    shortDescription:
      "National campaigns and school outreach to drive new participants into local clubs.",
    benefitOffered: "Co-branded open day toolkit",
    benefitType: "service_bundle",
    website: "https://joinin.example.com",
    contactEmail: "partners@joinin.example.com",
    contactPhone: "",
    logoDataUrl: null,
    offer: {
      title: "Open day campaign kit",
      description:
        "Templates, posters and social assets for a successful try-a-session event.",
      terms: "Draft partnership — pending final approval.",
      promoCode: "",
      validUntil: monthsAhead(12),
    },
    status: "draft",
    recommended: false,
    isNew: false,
    analytics: { views: 0, clicks: 0, claims: 0, introductions: 0 },
    createdAt: daysAgo(2),
    updatedAt: daysAgo(2),
  },
];

export const SEED_PARTNER_CLAIMS: PartnerClaim[] = [
  {
    id: "pclaim_demo1",
    partnerId: "partner_sportequip",
    partnerName: "SportEquip Pro",
    type: "claim",
    clubId: "club_demo",
    clubName: "Riverside FC Juniors",
    contactName: "Sarah Mitchell",
    contactEmail: "sarah@riversidefc.example.com",
    message: "Claimed equipment discount for new season kit.",
    createdAt: daysAgo(4),
  },
  {
    id: "pclaim_demo2",
    partnerId: "partner_clubcover",
    partnerName: "ClubCover Insurance",
    type: "introduction",
    clubId: "club_demo2",
    clubName: "Elm Dance Academy",
    contactName: "James Chen",
    contactEmail: "james@elmdance.example.com",
    message: "Requested introduction to discuss liability cover renewal.",
    createdAt: daysAgo(2),
  },
];
