import type { ClubDiscount, DiscountRedemption } from "./types";

export const DEMO_PROVIDER_ID = "demo";

export const DEFAULT_DISCOUNTS: ClubDiscount[] = [
  {
    id: "disc-1",
    providerId: DEMO_PROVIDER_ID,
    kind: "promo",
    name: "Summer camp early bird",
    code: "SUMMER10",
    type: "percentage",
    value: 10,
    appliesTo: "holiday_camp",
    appliesToLabel: "Summer holiday camps",
    minimumSpend: 0,
    usageLimitTotal: 100,
    usageLimitPerParent: 1,
    startDate: "2026-05-01",
    endDate: "2026-08-31",
    canCombine: false,
    isActive: true,
    isPaused: false,
    isArchived: false,
    redemptionCount: 18,
    totalDiscountedAmount: 162,
    createdAt: "2026-04-15T10:00:00.000Z",
    updatedAt: "2026-06-10T14:20:00.000Z",
  },
  {
    id: "disc-2",
    providerId: DEMO_PROVIDER_ID,
    kind: "promo",
    name: "New parent welcome",
    code: "WELCOME5",
    type: "fixed",
    value: 5,
    appliesTo: "all_activities",
    minimumSpend: 15,
    usageLimitTotal: null,
    usageLimitPerParent: 1,
    startDate: "2026-01-01",
    endDate: null,
    canCombine: false,
    isActive: true,
    isPaused: false,
    isArchived: false,
    redemptionCount: 42,
    totalDiscountedAmount: 210,
    createdAt: "2025-12-20T09:00:00.000Z",
    updatedAt: "2026-06-13T11:05:00.000Z",
  },
  {
    id: "disc-3",
    providerId: DEMO_PROVIDER_ID,
    kind: "promo",
    name: "Saturday football trial",
    code: "FOOTBALL20",
    type: "percentage",
    value: 20,
    appliesTo: "selected_activity",
    appliesToLabel: "Saturday football",
    minimumSpend: 0,
    usageLimitTotal: 25,
    usageLimitPerParent: 1,
    startDate: "2026-06-01",
    endDate: "2026-06-30",
    canCombine: false,
    isActive: true,
    isPaused: false,
    isArchived: false,
    redemptionCount: 7,
    totalDiscountedAmount: 35,
    createdAt: "2026-05-28T16:00:00.000Z",
    updatedAt: "2026-06-12T08:30:00.000Z",
  },
  {
    id: "disc-4",
    providerId: DEMO_PROVIDER_ID,
    kind: "promo",
    name: "After-school loyalty",
    code: "AFTERSCHOOL",
    type: "fixed",
    value: 3,
    appliesTo: "after_school_club",
    minimumSpend: 20,
    usageLimitTotal: 50,
    usageLimitPerParent: 2,
    startDate: "2026-06-20",
    endDate: "2026-07-15",
    canCombine: false,
    isActive: false,
    isPaused: false,
    isArchived: false,
    redemptionCount: 0,
    totalDiscountedAmount: 0,
    createdAt: "2026-06-01T12:00:00.000Z",
    updatedAt: "2026-06-01T12:00:00.000Z",
  },
];

export const DEFAULT_REDEMPTIONS: DiscountRedemption[] = [
  {
    id: "red-1",
    discountId: "disc-1",
    discountCode: "SUMMER10",
    parentName: "Helen Carter",
    parentEmail: "helen.carter@example.com",
    bookingId: "bk-101",
    bookingReference: "PV-2026-101",
    activityName: "Summer football camp",
    originalAmount: 90,
    discountAmount: 9,
    finalAmount: 81,
    redeemedAt: "2026-06-10T14:20:00.000Z",
  },
  {
    id: "red-2",
    discountId: "disc-2",
    discountCode: "WELCOME5",
    parentName: "James Okonkwo",
    parentEmail: "james.okonkwo@example.com",
    bookingId: "bk-102",
    bookingReference: "PV-2026-102",
    activityName: "Mini tennis",
    originalAmount: 18,
    discountAmount: 5,
    finalAmount: 13,
    redeemedAt: "2026-06-11T09:45:00.000Z",
  },
  {
    id: "red-3",
    discountId: "disc-3",
    discountCode: "FOOTBALL20",
    parentName: "Priya Sharma",
    parentEmail: "priya.sharma@example.com",
    bookingId: "bk-103",
    bookingReference: "PV-2026-103",
    activityName: "Saturday football",
    originalAmount: 25,
    discountAmount: 5,
    finalAmount: 20,
    redeemedAt: "2026-06-12T08:30:00.000Z",
  },
];
